### ISSUE TITLE
[BUG] Shading is weird on SteamVR controllers in Beta 1.16.8

### ISSUE THREAD

**Issue by happysmash27** [ValveSoftware/SteamVR-for-Linux#430] opened 2021-02-26 07:29 UTC
**Describe the bug**
After the beta 1.16.8, the controllers appear to be... semi-see-through? They look like as follows: 
![2021-02-22-222309_1280x1017_scrot](https://user-images.githubusercontent.com/3620657/109268394-dc18be00-77bf-11eb-8e14-60eb57b0699e.png)

**To Reproduce**
1. Open SteamVR. 
2. Turn on controllers. 
3. Before the home has loaded in, or while loading games, the controllers will look very weird. 

**Expected behavior**
The controllers will look normal and solid. 

**System Information (please complete the following information):**
- Distribution: Gentoo, kernel 5.11.0-gentoo
- SteamVR version: 1.16.8
- Steam client version: Feb 12, 2021, 23:22:26
- Opted into Steam client beta?: Launcher, no, SteamVR, yes. 
- Graphics driver version:  [run `nvidia-settings` or `vulkaninfo | grep driverInfo`: Mesa 21.0.0-rc3 (ACO)
- Gist for SteamVR System Information: https://gist.github.com/happysmash27/1124857ee107f347fa78f04559444a07

**Screenshots**
![2021-02-22-222309_1280x1017_scrot](https://user-images.githubusercontent.com/3620657/109268394-dc18be00-77bf-11eb-8e14-60eb57b0699e.png)

**Additional context**
This problem did not exist on version 1.16.7. 

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment] 2021-02-26 12:45
Rendering of base stations also also have an inverted z-depth look.

**Comment by HadetTheUndying** [comment] 2021-03-08 06:42
I'm sure this is a no brainer to whichever Dev looks at this in the future, but this is definitely a draw ordering issue probably related to alpha blending. Is this also happening on AMD? I'm still waiting on my Index to ship and can test it then.

**Comment by akuhtr** [comment] 2021-03-08 07:03
> I'm sure this is a no brainer to whichever Dev looks at this in the future, but this is definitely a draw ordering issue probably related to alpha blending. Is this also happening on AMD? I'm still waiting on my Index to ship and can test it then.

Yes, its also on AMD. My rx 5700 have same issue.

**Comment by Goofybud16** [comment] 2021-03-08 08:44
Confirmed here as well
RX 5700XT
Debian Testing Mesa 20.3.4

**Comment by happysmash27** [comment] 2021-03-10 13:02
> Is this also happening on AMD? I'm still waiting on my Index to ship and can test it then.

The original bug report was for AMD; I use an RX 480.

**Comment by ChrisJAllan** [comment] 2021-03-11 04:43
Still an issue in 1.16.9 beta.
RX 5700 Mesa 20.3.4

**Comment by ZarathustraDK** [comment] 2021-03-14 12:43
Got the same issue on a RX 6800 XT.

**Comment by HadetTheUndying** [comment] 2021-03-23 18:38
Issue is present in the latest Stable and Beta for me. Also having the same weird behavior with overlays. Think there might be something wonked out with Draw Ordering.

**Comment by mmcnutt** [comment] 2021-03-25 23:46
I also have this issue on Fedora 34 with a 5700XT latest mesa-git

admittedly I think it looks kind of cool

**Comment by melvyn2** [comment] 2021-03-31 23:48
All of the z-ordering for steamvr overlays is inverted for me too, latest stable mesa + rx 580.

**Comment by timcarr89** [comment] 2021-04-03 02:03
Same with with the Index controllers. They look like the face normals are inside-out. (slightly hard to see in still images, but very evident in motion)
![index](https://user-images.githubusercontent.com/8944961/113465015-f0735a80-93fe-11eb-80c0-734b3a1e299b.jpg)

**Comment by mathew2214** [comment] 2021-04-03 02:04
i also have this issue. 
rx 5700 mesa 20.3.4

**Comment by podiki** [comment] 2021-07-10 23:01
Can confirm with a 6700 XT, mesa 21.1.4 (and mesa-git), SteamVR beta branch. Something with the normals and/or depth on the controllers.

**Comment by dirkson** [comment] 2021-08-12 17:34
I also have this issue. Are we 100% sure this isn't the intended new look?

**Comment by Scrumplex** [comment] 2021-08-12 18:40
> I also have this issue. Are we 100% sure this isn't the intended new look?

afaik SteamVR on Windows doesn't have this

**Comment by podiki** [comment] 2021-08-12 19:01
> I also have this issue. Are we 100% sure this isn't the intended new look?

Ha! See-through could be cool, but it is clearly a depth/normal vector rendering issue: controllers appear behind interface elements like menus and the Steam interface.

Still seeing this on the latest beta, any updates?

**Comment by HadetTheUndying** [comment] 2021-08-12 20:32
Definitely still happening in the latest beta.

**Comment by RoboMolluskKing** [comment] 2021-09-02 21:48
I, too, have this issue for weeks. I am in the latest SteamVR beta (1.19.7 as I typed this). SteamVR beta (and stable) on Windows has no issues at all.

I am on Debian Sid, my GPU is an AMD RX 570 (Mesa 21.2.1)

It's not just the controllers, the base stations are also having it as well

![base](https://user-images.githubusercontent.com/68045246/131918241-855e3f39-7c7b-41f6-a2c0-32310c629023.png)
![controllers](https://user-images.githubusercontent.com/68045246/131918246-582e6855-94c7-4d21-bf4a-83f6f31e84d8.png)

**Comment by HadetTheUndying** [comment] 2021-09-03 20:29
I have a feeling this is probably an issue with a version of llvm or mesa SteamVR is being compiled against for the Linux builds.

**Comment by Goofybud16** [comment] 2021-09-21 02:47
Wanted to update my confirmation, also an issue on a 6700XT and Mesa 21.2.1 and SteamVR 1.19.7.

**Comment by gameboycjp** [comment] 2021-11-20 19:56
Putting in my confirmation, RX 6600 XT, Mesa 21.2.5, SteamVR Beta 1.21.2.

**Comment by Meister1593** [comment] 2021-11-23 20:56
Same thing for me
XFX RX480 4 GB, 
mesa 21.2.5,
SteamVR Stable 1.20.4, 
Kernel 5.15.2-tkg-pds_21
Distro: Bedrock linux (main/init distro/strata - void, secondary - arch)

**Comment by Supreeeme** [comment] 2022-03-12 18:53
I wonder if this is an AMD specific bug. This was not happening with my GTX 1060 but when I switched to an RX 6600 I started seeing this.

**Comment by oemsysadm** [comment] 2022-03-14 03:33
Manjaro/Gnome with an rx6800xt, same issue.

**Comment by RoboMolluskKing** [comment] 2022-03-14 06:44
I may have found a temporary fix for the time being

According to Tech Pills from May of last year, he also experienced the same bug as well (see the timestamp here: https://youtu.be/3C1dl8pKzpU?t=179). As he mentioned around 8:06, you need to roll into SteamVR beta build `linux_v1.14`.

Also I don't know if it is just me, but for some reason in this build, my system menu does not pop up when I press my system menu button on my controller, there is a weird double ghosting effect when I move my head or controllers around, and any VR game can't be launched.

**Comment by okawo80085** [comment] 2022-03-16 08:54
> As he mentioned around 8:06, you need to roll into SteamVR beta build `linux_v1.14`.
>
> Also I don't know if it is just me, but for some reason in this build, my system menu does not pop up when I press my system menu button on my controller, there is a weird double ghosting effect when I move my head or controllers around, and any VR game can't be launched.

Not a good fix, not by a long shot at least, most of your issues were fixed in later versions of SteamVR, rolling back 7 versions is bound to bring old bugs that are more annoying than weird controller shading (as you've noticed already, stuttering and ghosting, those were mostly fixed in later versions).

A better way to approach this issue is try to find the shader thats used for overlay controller rendering, and try to run it in an isolated test, it's a vulkan shader obviously so it's not gonna be easy, but you'll be able to debug it and see if it's an AMD vulkan issue or an issue specific to that shader on AMD *and* try to fix it.
This way the fix for this issue could be integrated into the future releases of SteamVR 

I'd do it myself, but i have no access to an AMD gpu nor do i have access to any of my VR stuff right now.

**Comment by Meister1593** [comment] 2022-03-16 09:19
> > As he mentioned around 8:06, you need to roll into SteamVR beta build `linux_v1.14`.
> > Also I don't know if it is just me, but for some reason in this build, my system menu does not pop up when I press my system menu button on my controller, there is a weird double ghosting effect when I move my head or controllers around, and any VR game can't be launched.
> 
> Not a good fix, not by a long shot at least, most of your issues were fixed in later versions of SteamVR, rolling back 7 versions is bound to bring old bugs that are more annoying than weird controller shading (as you've noticed already, stuttering and ghosting, those were mostly fixed in later versions).
> 
> A better way to approach this issue is try to find the shader thats used for overlay controller rendering, and try to run it in an isolated test, it's a vulkan shader obviously so it's not gonna be easy, but you'll be able to debug it and see if it's an AMD vulkan issue or an issue specific to that shader on AMD _and_ try to fix it. This way the fix for this issue could be integrated into the future releases of SteamVR
> 
> I'd do it myself, but i have no access to an AMD gpu nor do i have access to any of my VR stuff right now.

In case you need any help, I have both amdgpu and vive to test with

**Comment by okawo80085** [comment] 2022-03-16 10:26
> In case you need any help, I have both amdgpu and vive to test with

Awesome! I'll try to isolate the shader used for controllers and make a test case when i'm free from work.

**Comment by CobaltSpace** [comment] 2023-03-29 19:46
It appears to be fixed for me in SteamVR Beta 1.26.1.

**Comment by caseif** [comment] 2023-03-29 20:24
Can confirm it's fixed on my end as well with 1.26.1!

**Comment by RoboMolluskKing** [comment] 2023-03-31 07:32
A few GPU artifacts like the home menu on my left Index controller or how sluggish it is when I use it, how it's not launching the room setup, and how the sound is not coming from my headset, aside from all of that, I too confirm that it works. It's about time! (1.26.1)

**Comment by kisak-valve** [comment] 2023-05-19 19:40
Hello @RoboMolluskKing, your follow up issues should be reported and tracked separately.

Closing as fixed.

**Closed by kisak-valve** 2023-05-19 19:40 UTC
Labels: bug, Need Retest
