### ISSUE TITLE
[PERF] Display response time is extremely high.

### ISSUE THREAD

**Issue by 2-3-5-41** [ValveSoftware/SteamVR-for-Linux#535] opened 2022-09-07 15:21 UTC
**Describe the bug**
When trying out VR once again on linux using the Valve Index, I've noticed that this issue is still going on; whether I use Steam(Runtime), Steam(Native), SteamVR(beta), SteamVR(stable), SteamVR(Older build for linux users), my HMD's response time is way to high, making the view in the hmd lag behind where my actual gaze should be, creating this dizzying effect in the headset that strains the eyes. I've also noticed that frame times are way higher than what I had on windows, especially when not in steamvr home or any vr apps (on windows = >1 or 1ms at 90hz, on arch linux <3ms at 90hz).

**To Reproduce**
1. Run Arch linux with the latest LTS linux kernal
2. Use Steam Runtime (or native)
3. Run SteamVR (beta, stable, or older linux build)
4. Long response time view.

**Expected behavior**
From the experience I had on Windows 10 and 11, I expected my view to have a 1 to >1 ms response time.

**System Information (please complete the following information):**
- Distribution: [Arch/Manjaro/Ubuntu/etc.] Arch (LTS Kernel)
- SteamVR version: 1.23.7 & linux_v1.14
- Steam client version: Aug 31 2022, at 04:28:42 
- Opted into Steam client beta?: [Yes/No] Yes
- Graphics driver version:  [run `nvidia-settings` or `vulkaninfo | grep driverInfo`: Mesa 22.1.7
- Gist for SteamVR System Information: [System Report](https://gist.github.com/1SMOL/603e01bac2d3015005e190adce1599fd)

**Performance Data (optional, but very helpful):**
- CPU: AMD Ryzen™ 9 5900X × 24
- GPU: AMD Radeon™ RX 6800 XT
- Gist for perf top: n/a
- Link to gpuvis trace: n/a

Could not perform the last two instructions due to SteamVR(beta), SteamVR(Stable), and SteamVR(Linux_v1.14) not providing the options described in the instruction set.

**Screenshots**
![image](https://user-images.githubusercontent.com/93025618/188916033-b566c717-edf8-4e07-b58d-0288a720981f.png)

**Additional context**
n/a

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" and "Perf Data" sections in their replies.

**Comment by Taiko2k** [comment] 2022-09-28 07:51
Likely the async reprojection issue. The workaround here https://github.com/ValveSoftware/SteamVR-for-Linux/issues/227#issuecomment-520459572 fixes the major lag for me. Though other reprojection issues affecting performance still remain #395. #469 could also be affecting performance.

Unfortunately there doesn't seem to be any movement from Valve on these in over a year.

**Comment by 1SMOL** [comment] 2022-10-01 01:59
Disabling async reprojection globally through the `.vrsettings` file yielded no result for me. Also the issue #395 is exactly what I experience, but it's not only effecting the vr overlay, it's effecting the entire display/rendered frame.

**Comment by 2-3-5-41** [comment] 2023-09-21 18:25
Update on this issue:
The high frame time is resolved by using `corectrl` and setting my GPU to it's VR power profile, an upping its GPU and memory speeds to their "normal" compared to speeds on windows.

Hope this resolves other's issues of poor performance while on an AMD system.

**Comment by kisak-valve** [comment] 2023-09-21 18:27
Hello @2-3-5-41, that makes this issue report a duplicate of #469. Closing in favor of the older issue report.

**Closed by kisak-valve** 2023-09-21 18:27 UTC
Labels: perf
