### ISSUE TITLE
Dashboard not working properly

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/SteamVR-for-Linux#119] opened 2018-08-07 19:30 UTC
#### Your system information
* Steam client version (build number or date): latest Steam beta as of 07.08.2018
* Distribution (e.g. Ubuntu): (K)Ubuntu 18.04
* Graphics driver version (run nvidia-settings): Using RX 580 with Mesa 18.1.5 from the padoka PPA
* Gist for SteamVR System Information: https://gist.github.com/Zamundaaa/d8d86a5b7aef0f88341f27d865428656
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamVR beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
The dashboard doesn't show most of the time in the latest SteamVR beta 1533664367. The grey bar at the bottom is visible, but none of the menu buttons are. Also the Steam Big Picture and desktop view never worked. Similar to issue #75 but input to the desktop view doesn't work either, mouse is stuck at the upper left corner of the screen. Sometimes I can open the settings by pressing that unseen button, and then sometimes it shows up, but most of the time it doesn't.
The power down menu does work, if I press the (now invisible) button it appears. But I can't actually use it, as using the button exit VR doesn't do anything

#### Steps for reproducing this issue:
1. Start SteamVR
2. Open Dashboard

**Comment by lubosz** [comment] 2018-08-09 11:40
I can reproduce the issue with current SteamVR beta and stable (which are apparently the same).
The dashboard fails to draw it's UI, but it is visible for one frame upon the first opening.
Other overlays (Library/Desktop/Custom) also have the flickering issue, but I was able to see the desktop overlay correctly after multiple tries. The dashboard is still sensitive to input.

System:
```
Steam Beta Client
Arch Linux
Linux 4.18
Mesa master fcf259ef97fef9d52e7f82ef90fb2383438743b3
Also AMD RX 580
```

SteamVR Stable / Beta version
```
Built Aug 7, 2018 at 19:52
Version 1533664367
```

The issue is not reproducible with the older `1527117754` build available.

**Comment by lubosz** [comment] 2018-08-10 12:41
Seems to be fixed in `1533861641`

**Comment by Zamundaaa** [comment] 2018-08-10 14:16
Yes it does show up again. So the regression is fixed. But I still can't see Steam or my Desktop and "Exit VR" doesn't work either

**Comment by lostgoat** [comment] 2018-08-10 15:17
@Zamundaaa those overlays come from the steam client, make sure your steam client has a 32bit vulkan driver available.

**Closed by lostgoat** 2018-08-10 15:17 UTC

**Comment by Zamundaaa** [comment] 2018-08-10 16:05
@lostgoat ah thank you very much. I had only 64 bit vulkan installed, this fixed it. Desktop view shows only single single screens, uses the display as input for all 3 of them, and I can view the extended display (not really a big issue, looks funny) but works fine. Steam works fine now, too. "Exit VR" doesn't work still

**Comment by kisak-valve** [comment] 2018-08-13 13:08
Hello @Zamundaaa, please open a separate issue report for vrdashboard calling xdg-open, which in turn calls kde-open and kde-open falls over from some environment variables set for SteamVR's use.
