### ISSUE TITLE
vrwebhelper.sh affected by steam-for-linux#7935

### ISSUE THREAD

**Issue by Patola** [ValveSoftware/SteamVR-for-Linux#465] opened 2021-09-14 02:49 UTC
**Describe the bug**
In the VR screen, pressing the system buttons do not bring up the SteamVR Overlay anymore. On the SteamVR steam window, selecting the burger menu, then "Settings" won't show the settings dialog anymore either. Tried changing from SteamVR stable to beta and back, tried Room Setup (which works and completes), but nothing seems to get the SteamVR Overlay to work again.

**To Reproduce**
1. Start SteamVR
2. In the steamvr status windows, select the burger menu, then settings. The settings window will not appear.
3. In VR, try pressing the system button to bring up the SteamVR overlay. It won't work.

**Expected behavior**
The settings dialog should work. The SteamVR overlay should work.

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: 1.19.7
- Steam client version: Built Sep 13 2021, at 22:01:31
- Opted into Steam client beta?: Yes and No. Tried both.
- Graphics driver version: Mesa 21.2.1
- Gist for SteamVR System Information: https://gist.github.com/Patola/5039e252617315a6b2cd09cd79f23dec

**Additional context**
I use OVR Advanced Settings to augment SteamVR. I cannot remove it from autostarting since I cannot get to the settings window. But I tried to uninstall OVR Advanced Settings to run SteamVR without it and got the same result.

Notice that SteamVR still works and calls SteamVR home, which also works, and the VR games still play. It's the settings and the overlay that are not working. I haven't changed any SteamVR settings pior to that happening. It's been about a week this way.

I have noticed that the steamtours, vrmonitor and vrdashboard processes each create a defunct [vrwebhelper] process.

I am also attaching some logs from under ~/.steam/steam/logs/ that I think might be useful, in a zipped file.
[steam-vr-logs.zip](https://github.com/ValveSoftware/SteamVR-for-Linux/files/7158551/steam-vr-logs.zip)

**Comment by Patola** [comment] 2021-09-14 16:05
Is there at least a workaround I could do to "reset" my SteamVR and make the overlay work again? If possible by not losing my controller bindings configurations.

**Comment by bmorgz** [comment] 2021-09-15 01:02
I have been having the same problem, but I'm not sure if I was ever able to open the settings or overlay on Linux since I started using it recently. I tried switching to the beta and back, verifying the files and reinstalling but this did not fix the issue. I also tried with and without the Steam client beta. I am using Arch Linux with ALVR.

I think the config files are in `~/.local/share/Steam/config`. You may or may not need to back them up.

**Comment by farmboy0** [comment] 2021-09-15 11:47
For me the systems menu in VR only shows on the second start of SteamVR, have you tried starting SteamVR, exiting after Steam Home loaded and start it again and if it works then?

**Comment by Patola** [comment] 2021-09-15 11:55
Yes, I have. Started it many times and neither the settings dialog in the screen nor the overlay in the VR headset come up. :-(
I see a lot of logfiles under ~/.steam/steam/logs, as soon as I have time I will peruse them for any clue. I do think it might be related to me pressing "PLAY" on OVR Advanced Settings on steam accidentally. Maybe two running instances of the same software corrupted some metadata and made this happen.

**Comment by wallcarpet40** [comment] 2021-09-15 12:02
This is probably the same issue as with #255 
You could try this: https://github.com/ValveSoftware/SteamVR-for-Linux/issues/255#issuecomment-775624892
It did not work for me, but after installing Kubuntu, it has been working more reliably and usually can be fixed by restarting SteamVR.

**Comment by Patola** [comment] 2021-09-15 12:43
> This is probably the same issue as with #255
> You could try this: [#255 (comment)](https://github.com/ValveSoftware/SteamVR-for-Linux/issues/255#issuecomment-775624892)
> It did not work for me, but after installing Kubuntu, it has been working more reliably and usually can be fixed by restarting SteamVR.

Thanks for the attempt at a solution. I tried the solution expressed and then the SteamVR dialog wouldn't even appear. had to unmake the link `~/.steam/steam/steamapps/common/SteamVR/bin/linux64/qt/plugins` and restore the old `plugins.old` to `plugins` for the dialog to even appear.

**Comment by Patola** [comment] 2021-09-16 00:26
Well, `vrwebhelper` wasn't starting due to an unknown symbol in `libfreetype6.so`. Downgrading the package `freetype2` solved the issue. * facepalm * Now the overlay works correctly.

**Comment by fazo96** [comment] 2021-09-26 18:59
Hey @Patola I am also on Arch and I have the same issue. I have freetype2 version 2.11.0-4. To which version did you downgrade to get it to work?

Did downgrading freetype2 fix the entire issue for you meaning the settings dialog and VR overlay both work now?

**Comment by Pokeduel** [comment] 2021-09-27 01:46
@fazo96 downgrading to at least 2.10.4 seemed to work for me.

**Comment by frostworx** [comment] 2021-10-01 12:11
Instead of doing a system-wide freetype downgrade, I copied
- libfreetype.so _(symlink)_
- libfreetype.so.6 _(symlink)_
- libfreetype.so.6.17.4  _(file)_

into `vrwebhelper/linux64/`
and changed
`export LD_LIBRARY_PATH="${STEAM_RUNTIME_HEAVY}${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}"`
to
`export LD_LIBRARY_PATH="${DIR}:${STEAM_RUNTIME_HEAVY}${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}"`

in `vrwebhelper.sh`

In a quick test the dashboard works.

_(of course maintained binaries or open sourcing everything linux vr related as far as possible would be a better aproach)_

**Comment by Termuellinator** [comment] 2021-10-02 11:34
i can confirm that frostworx workaround works for the dashboard and the settings window to show up again, thanks buddy! :+1:

**Comment by podiki** [comment] 2021-11-05 01:31
Can report the workaround did it for me too, with Flatpak Steam (no difference other than the folders being different for where Flatpak Steam keeps things).

**Comment by Bitwolfies** [comment] 2021-12-26 21:40
The fact we've had to manually fix a core part of steamvr since September is incredibly disappointing.

**Comment by TheDrawingCoder-Gamer** [comment] 2021-12-27 21:00
This workaround does cause the menu work; As Bitwolfies said it is very disappointing; The community knows the issue so there really is no reason for this to happen

**Comment by TheDrawingCoder-Gamer** [comment] 2021-12-27 21:23
However it moves around a lot (which iirc it doesn't do on windows) : (

**Comment by Bitwolfies** [comment] 2021-12-28 07:30
Sadly the work around fails for me, causing my whole pc to reboot when trying to run SteamVR, valve really needs to get a fix out.

**Comment by Bitwolfies** [comment] 2022-01-12 11:47
Newest beta mentions a fix!

**Comment by frostworx** [comment] 2022-01-12 12:12
> Newest beta mentions a fix!

Fairlight (when dreams come true)

**Comment by Bitwolfies** [comment] 2022-01-12 12:40
Sigh, even after a full reninstall, after trying that "fix" posted above, steamvr resets my pc on boot, I have no idea how to undo this whatsoever.

**Comment by okawo80085** [comment] 2022-01-12 13:30
>  Vrcompositor boots for maybe half a second, before kicking my pc to the arch startup terminal, and then my DE login.

AHAH! `vrcompositor` has this weird tendency to crash, sometimes with sigsegv, can you by any chance get core dump logs for `vrcompositor` right before your DE crashed?

**Comment by kisak-valve** [comment] 2022-01-12 13:44
As @Bitwolfies noted, the [SteamVR 1.21.5 Beta](https://store.steampowered.com/news/app/250820/view/3126061077819506317) update includes "Fixed webhelper crashing in OS's with recent versions of freetype2." Please opt into SteamVR's beta branch and retest.

**Comment by Bitwolfies** [comment] 2022-01-12 13:50
> As @Bitwolfies noted, the [SteamVR 1.21.5 Beta](https://store.steampowered.com/news/app/250820/view/3126061077819506317) update includes "Fixed webhelper crashing in OS's with recent versions of freetype2." Please opt into SteamVR's beta branch and retest.

Wish I could, but now I'm being effected by https://github.com/ValveSoftware/SteamVR-for-Linux/issues/489

**Comment by azkanel** [comment] 2022-01-12 19:47
> As @Bitwolfies noted, the [SteamVR 1.21.5 Beta](https://store.steampowered.com/news/app/250820/view/3126061077819506317) update includes "Fixed webhelper crashing in OS's with recent versions of freetype2." Please opt into SteamVR's beta branch and retest.

I just tried and SteamVR Overlay does not appear ...

**Comment by ZarathustraDK** [comment] 2022-01-12 22:20
Tested the beta, it seems to work for me consistently now. I have started Steamvr 3 times in a row and every time I'm capable of spawning the overlay (was rarely able to do it even once on the newest release build). Other problems are still there though (Desktop-view crapping out/having graphical corruption, the async reprojection doing the wrong frames, and I noticed in games that the async reprojection "haze" is back (kind of like the little brother of the big async reprojection problem people experience in the game-loading/transition screen. It has a constant high frequency though making the effect appear smooth, and the reprojection is only a little off, making stuff appear blurry rather than jumpy/jarring when looking at stuff while moving your head).

Ryzen 5900x
AMD 6800XT
Arch Linux

**Comment by kisak-valve** [comment] 2022-01-13 18:13
SteamVR 1.21.5 added the library pinning logic which fixed steam-for-linux#7935, but it's looking in the wrong place for the steam-runtime-heavy libraries because `STEAM_RUNTIME_HEAVY` is not set.

For now, adding `STEAM_RUNTIME_HEAVY="${HOME}/.steam/bin64/steam-runtime-heavy" %command%` to SteamVR's launch options should workaround that quirk until a SteamVR developer can take a look.

**Comment by okawo80085** [comment] 2022-01-13 18:51
> SteamVR 1.21.5 added the library pinning logic which fixed steam-for-linux#7935, but it's looking in the wrong place for the steam-runtime-heavy libraries because `STEAM_RUNTIME_HEAVY` is not set.
> 
> For now, adding `STEAM_RUNTIME_HEAVY="${HOME}/.steam/bin64/steam-runtime-heavy" %command%` to SteamVR's launch options should workaround that quirk until a SteamVR developer can take a look.

Dashboard works again after adding the suggested changes to SteamVR's launch options! I will run a few longer tests though.

**Comment by azkanel** [comment] 2022-01-13 23:10
Dashboard won't work for me. Appears all dashboard with colored squared like with steamvr 1.21.5
My system:
ubuntu 21.10
kernel 5.16
mesa 21.3.3
Radeon RX 580
freetype 2.10.4

**Comment by kisak-valve** [comment] 2022-01-13 23:29
Hello @azkanel, your symptoms don't match this issue report.

That set aside, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by podiki** [comment] 2022-01-14 01:20
Neither the update or with the launch options did I get the VR dashboard with Flatpak Steam or (non)Guix's Steam. Both are run in containers, which complicates the runtimes, so maybe that is something on that end rather than with SteamVR. I'll have to investigate or open an issue separately if this otherwise works on regular Steam.

**Comment by azkanel** [comment] 2022-01-16 22:46
> Hello @azkanel, your symptoms don't match this issue report.
> 
> That set aside, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

<script src="https://gist.github.com/azkanel/699eb3bdaf89e8baeb3ec69fd49a1ca7.js"></script>

**Comment by kisak-valve** [comment] 2022-01-16 23:31
Thanks @azkanel, your system looks healthy overall.

I've got a guess that either Steam or SteamVR is getting run on your iGPU while the other is running on the dGPU and that's causing trouble with the OpenGL to Vulkan interop that happens with vrdashboard. I've not used it myself, but maybe try completely closing Steam, then run `steam` from a terminal and setting SteamVR 1.20.4's launch options to `MESA_VK_DEVICE_SELECT=1002:67df %command%` (based on the discussion [here](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/1766)).

In theory, that should at least avoid the issue being tracked here, and https://github.com/ValveSoftware/steam-for-linux/issues/7089#issuecomment-903155719 and more predictably have both running on the RX 580.

If that doesn't give you a working reference point to start from, then please open a new issue report.

**Comment by azkanel** [comment] 2022-01-17 20:00
> Thanks @azkanel, your system looks healthy overall.
> 
> I've got a guess that either Steam or SteamVR is getting run on your iGPU while the other is running on the dGPU and that's causing trouble with the OpenGL to Vulkan interop that happens with vrdashboard. I've not used it myself, but maybe try completely closing Steam, then run `steam` from a terminal and setting SteamVR 1.20.4's launch options to `MESA_VK_DEVICE_SELECT=1002:67df %command%` (based on the discussion [here](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/1766)).
> 
> In theory, that should at least avoid the issue being tracked here, and [ValveSoftware/steam-for-linux#7089 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/7089#issuecomment-903155719) and more predictably have both running on the RX 580.
> 
> If that doesn't give you a working reference point to start from, then please open a new issue report.

I am very grateful for your help. I will open a new topic

**Comment by Bitwolfies** [comment] 2022-01-22 06:03
Was finally able to get back in, can confirm this patch works just fine, even without the command fix, great to see!

**Comment by kisak-valve** [comment] 2022-01-22 14:17
Please retest without the `STEAM_RUNTIME_HEAVY` workaround.

**Comment by wallcarpet40** [comment] 2022-01-22 15:30
I can report that SteamVR dashboard menu now works without the `STEAM_RUNTIME_HEAVY` workaround. Tested with Fedora 35 and Arcolinux.

**Comment by Bitwolfies** [comment] 2022-01-22 19:37
> I can report that SteamVR dashboard menu now works without the `STEAM_RUNTIME_HEAVY` workaround. Tested with Fedora 35 and Arcolinux.

+1, works fine on arch without workarounds

**Comment by okawo80085** [comment] 2022-01-23 03:04
> I can report that SteamVR dashboard menu now works without the `STEAM_RUNTIME_HEAVY` workaround. Tested with Fedora 35 and Arcolinux.

Same here, working a okay on Ubuntu 20.04 LTS without workarounds

**Closed** 2022-02-26 03:00 UTC
Labels: bug, Need Retest
