### ISSUE TITLE
`[BUG] Error 307 on Ubuntu studio 22.04 on NVIDIA 530.30.02 (beta, stable, legacy)`

### ISSUE THREAD

**Issue by ThaSwapMeetPimp** [ValveSoftware/SteamVR-for-Linux#601] opened 2023-08-16 05:54 UTC
**Describe the bug**
Error 307 on beta, stable, and 1.14 for linux users
**To Reproduce**
1. Go to SteamVR 
2. Click on Launch
3. SteamVR starts with error 307

**Expected behavior**
SteamVR starting without error 307 and displaying in my Index
**System Information (please complete the following information):**
- Distribution: [Arch/Manjaro/Ubuntu/etc.] Ubuntu Studio 22.04
- SteamVR version: [E.g. 1.7.2] Current Beta 1.27.1, Current  Stable 1.26.7, and 1.14
- Steam client version: [build number or date] Steam Version:  1692041866
- Opted into Steam client beta?: [Yes/No] Yes
- Graphics driver version:  [run `nvidia-settings` or `vulkaninfo | grep driverInfo`: NVIDIA 530.30.02
- Gist for SteamVR System Information: [See [instructions](https://github.com/ValveSoftware/SteamVR-for-Linux/blob/master/CapturingSystemReport.md)]
- https://gist.github.com/ThaSwapMeetPimp/23d4a79f8c441e8830c43d3ebe2c2289

**Screenshots**

**Additional context**
Might be an issue with an upgrade to my system the other day and not SteamVR itself, as it was working before that, but I am at a loss as to how to fix. I am using CUDA Drivers on my 4090, and journalctl is showing a vrcompositor "segfault at 7f296170702d ip 00007f296170702d sp 00007ffd9a64ef98 error 14 in libnvidia-glvkspirv.so.530.30.02[7fc5f0400000+1487000] likely on CPU 10 (core 20, socket 0)" followed by "Code: Unable to access opcode bytes at 0x7f2961707003" and a little further down "kernel: traps: vrwebhelper[44772] trap int3 ip:7f4f98ebd50b sp:7ffdb91316f0 error:0 in libcef.so[7f4f94cec000+7770000]"

When I change to the latest drivers its a " vrcompositor[83813]: segfault at 7f296170702d ip 00007f296170702d sp 00007ffea6ff34a8 error 14 in libvulkan_lvp.so[7f3b39600000+59000]" followed by the opcode error but no libcef error in vrwebhelper.

It was showing SQLite database errors, but resetting tracker3 fixed that. I dont know what caused it. Like i was saying I just know it started after I did a system update. Any help would be appreciated as I am quite frustrated.
**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by Danielduel** [comment] 2023-08-16 08:32
In order to make this issue visible/searchable in bug tracker - I suggest changing the issue title to
`[BUG] Error 307 on Ubuntu studio 22.04 on NVIDIA 530.30.02 (beta, stable, legacy)`

Also - possible duplicate of https://github.com/ValveSoftware/SteamVR-for-Linux/issues/596

**Comment by kisak-valve** [comment] 2023-08-16 15:34
Hello @ThaSwapMeetPimp, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

The specific detail I'm looking to ponder is if you have a bleeding edge build of mesa on your system to go along with the lavapipe reference (libvulkan_lvp.so).

**Comment by ThaSwapMeetPimp** [comment] 2023-08-16 20:27
https://gist.github.com/ThaSwapMeetPimp/669c750ab08a4da28bd9b4769c7f573c

There you go. As towards having a bleeding edge build of mesa, I dont know. I have had to install a bunch of different stuff trying to get various peripherals, including my Index, to work with my rig since upgrading it.

**Comment by kisak-valve** [comment] 2023-08-16 20:42
https://gist.github.com/ThaSwapMeetPimp/669c750ab08a4da28bd9b4769c7f573c#file-gistfile1-txt-L559-L563 Looks like you have NVK, which doesn't exist in any mesa point release yet, so yes, you do have a bleeding edge mesa build. I suspect that your issue is related to https://gitlab.freedesktop.org/mesa/mesa/-/issues/9585 and it might be worthwhile to check in that direction.

**Comment by ThaSwapMeetPimp** [comment] 2023-08-16 22:43
> https://gist.github.com/ThaSwapMeetPimp/669c750ab08a4da28bd9b4769c7f573c#file-gistfile1-txt-L559-L563 Looks like you have NVK, which doesn't exist in any mesa point release yet, so yes, you do have a bleeding edge mesa build. I suspect that your issue is related to https://gitlab.freedesktop.org/mesa/mesa/-/issues/9585 and it might be worthwhile to check in that direction.

Hmmm.....checked into it, guess I'm going to have to figure out how to install the previous version of mesa and see if that will work. Thank you for the help

**Comment by ThaSwapMeetPimp** [comment] 2023-08-17 02:29
Thanks @kisak-valve. Quick ppa-purge of oibaf/graphics-drivers and I'm back in VR.

**Closed** 2023-08-17 02:29 UTC
Labels: bug
