### ISSUE TITLE
[BUG] vrcompositor `Failed to get blur texture lod 0` leading to error (500)

### ISSUE THREAD

**Issue by ThaSwapMeetPimp** [ValveSoftware/SteamVR-for-Linux#639] opened 2023-11-17 06:51 UTC
**Describe the bug**
SteamVR beta 2.1.3 shows "SteamVR Fail 
Oh no! SteamVR has encountered an unexpected 
problem
Restart SteamVR                                                             (500)

And nothing displays in headset.
**To Reproduce**
1. Go to 'SteamVR'
2. Click on 'Launch'
3. Wait to start
5. Restart SteamVR
6. See error
**Expected behavior**
SteamVR to work when launched
**System Information (please complete the following information):**
- Distribution: Ubuntu Studio 22.04
- SteamVR version: beta 2.1.3
- Steam client version: 1700160213
- Opted into Steam client beta?: Yes
- Graphics driver version: NVIDIA 535.129.03
- Gist for SteamVR System Information: http://gist.github.com/ThaSwapMeetPimp/1ee3c1d4c092668b93facf90701da793

**Screenshots**

**Additional context**

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by aureliensoria** [comment] 2023-11-17 08:08
Hello ! Same issue on my side. SteamVR crashes at startup with error 500.
OS: Pop!_OS 22.04 LTS
SteamVR: 2.1.3
Nvidia Driver: 545.29.02
Steam Beta: Yes

**Comment by kisak-valve** [comment] 2023-11-17 14:00
Hello @ThaSwapMeetPimp, these look like some lines of interest in your vrcompositor.txt log:
```
Thu Nov 16 2023 22:49:00.305172 [Error] - Failed to get blur texture lod 0
Thu Nov 16 2023 22:49:00.305182 [Error] - Failed to init graphics device
Thu Nov 16 2023 22:49:00.329178 [Info] - Failed to kill gpu-trace
Thu Nov 16 2023 22:49:00.332638 [Info] - Failed to initialize compositor
Thu Nov 16 2023 22:49:00.332666 [Info] - Failed to start compositor: VRInitError_Compositor_CreateBlurTexture
```

**Comment by caseif** [comment] 2023-11-17 14:06
I'm running into this issue as well on 2.1.3 with identical messages in the log.

**Comment by NewtSoup** [comment] 2023-11-17 15:54
Same as above.  2.13  - I have not been able to play VR games since late August.

**Comment by NewtSoup** [comment] 2023-11-17 16:45
if you switch away from the beta the live version is 2.0.10, that kind of works.  Skyrim at the very least is playable so I suspect that Ultrawings will be too.    We really need the ability to go back to  known working versions.    The last "good" version for me was 1.26 and I can't get the manual roll back to work. - Can we have  1.26 as a legacy roll back under the BETA's dropdown?

**Comment by Danielduel** [comment] 2023-11-17 23:18
Looks like I have the same issue.
Arch, Hyperland, latest everything

Attaching logs:
[SteamVR-2023-11-18-AM_12_14_56.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/13398233/SteamVR-2023-11-18-AM_12_14_56.txt)

Additional observation is that in terminal logs the steam has few failed sh calls
...
sh: 1: xdg-mime: not found
...
sh: 1: xdg-icon-resource: not found
sh: 1: xdg-mime: not found
...

**Comment by zatricky** [comment] 2023-11-18 02:33
This must have been caused by an update released very recently. I was playing games fine until a few hours ago. When I came back to Steam it was suddenly not working as described in this Issue. No system updates were done, no reboots/etc ; only Steam's automatic software updates. :-|

**Comment by caseif** [comment] 2023-11-18 03:12
@zatricky Yeah, it appears it was introduced in 2.1.3.

**Comment by icychkn** [comment] 2023-11-18 03:13
OS: Artix Linux (64 bit)
Kernel Version: 6.6.1-artix1-1
SteamVR: Beta
AMD Driver: AMD AMD Radeon RX 6700 XT (navi22, LLVM 16.0.6, DRM 3.54, 6.6.1-artix1-1)
AMD Driver Version: 4.6 (Compatibility Profile) Mesa 23.2.1-arch1.2
Steam Beta: Yes

Had the same issue with SteamVR Beta, but switching SteamVR to temp_v1.27.5 beta branch works flawlessly.

**Comment by c-x-berger** [comment] 2023-11-18 04:00
I'm now seeing a 500 error on startup of the stable branch - I'll edit this comment with system information in a moment.

**Comment by CarbonNotes** [comment] 2023-11-18 07:34
Not the ideal solution, of course, but utilizing the temp_1.27.5 Beta branch allows SteamVR to be usable again at the very least.

**Comment by ThaSwapMeetPimp** [comment] 2023-11-18 09:03
Great. Update on stable brings it up to 2.1.4, and this isnt fixed so SteamVR 2.x is completely borked.

**Comment by jnse** [comment] 2023-11-18 11:17
Same problem for me, same log messages. Both beta and stable. :(

**Comment by NewtSoup** [comment] 2023-11-18 11:42
@CarbonNotes > Not the ideal solution, of course, but utilizing the temp_1.27.5 Beta branch allows SteamVR to be usable again at the very least.

Thanks for this.  I tried it but no luck.  Issues for me started with the 1.27 release.  1.26 was the last known stable version I have played.

**Comment by andy-d1969** [comment] 2023-11-18 11:53
2.0.10 Stable worked fine here, now everything is broken. Please make 2.0.10 available in the beta menu.

**Comment by lightstream** [comment] 2023-11-18 12:42
Also suffering from this. My SteamVR System Report: https://gist.github.com/lightstream/327c7c8274ffb85de91ca6c28d887279

As others, the temp_1.27.5 Beta branch can be used as a workaround.

**Comment by Danielduel** [comment] 2023-11-18 12:54
> Great. Update on stable brings it up to 2.1.4, and this isnt fixed so SteamVR is completely borked on beta and stable.

Offtop...

"Stable"

I think it is time to do SteamVR version switcher 🤡

**Comment by andy-d1969** [comment] 2023-11-18 13:41
Like others said, 1.27.5 doesn't work here either. Only 1.15 works, but that is incompatible with newer Proton versions. 2.0.10 worked best here. So please make it available in the beta menu. I really need SteamVR to work.

**Comment by Danielduel** [comment] 2023-11-18 15:30
# SteamVR stable version downgrade

Go to steam and upgrade to "Beta participation None"

Get and check your SteamCMD
Docs `https://developer.valvesoftware.com/wiki/SteamCMD`
Try executing `steamcmd` in your shell, (if it is not available - install it) it should do it's thing and then give you an interactive shell with `Steam>` prefix.
Close it by `exit` and press enter.
(you can ignore `Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory`)

Current depots on my system (app meta in steam's subfolder):
SteamVR app id is `250820`
```jsonl
"250823"
{
	"manifest"		"3017499937843963703"
	"size"		"1058779236"
}
"250824"
{
	"manifest"		"4396900163967778263"
	"size"		"581278645"
}
"250827"
{
	"manifest"		"149537799382090177"
	"size"		"4816999"
}
"250830"
{
	"manifest"		"7851858840173054231"
	"size"		"3356665389"
}
"250832"
{
	"manifest"		"2989994424354254892"
	"size"		"365727352"
}
```
Compare them with manifest history: `https://steamdb.info/app/250820/depots/`
`250832`, `250830`, `250827` have depots from last month, I assume we can ignore them.
`250824`, `250823` most likely have the breaking change.

I pick version that is 17 or 18 days old
I pick `1399421998612179517` for `250823`
and `3630795351668562250` for `250824`
I suggest downgrading them both to prevent some random crash 2h into the vr session.

Depot download syntax:
`download_depot <appid> <depotid> [<target manifestid>] [<delta manifestid>] [<depot flags filter>]`

(You will have to pass your steam credentials and guard code to auth steamcmd)
```
steamcmd
login <username> <password>
download_depot 250820 250823 1399421998612179517
download_depot 250820 250824 3630795351668562250
```
(Those download_depot calls like to take longer than expected (they unpack a ton of small files), you can restart them, but you will have to repeat the login, if you think your download has stuck - you can inspect the depot folder size - see below)

`download_depot` will tell you where depots are stored, for me it was `~/.steam/steamcmd/linux32/steamapps/content/app_250820/`
Just to note - download size in the CLI and actual size after unpacking is different - 250823 for me showed 334MB, but after unpacking it is a bit less than 1010MB, 250824 is around 554MB after unpacking.

Steam's SteamVR directory:
* Flatpak steam: `~/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/SteamVR/`
* Native steam:
  `~/.local/share/Steam/steamapps/common/SteamVR/`

Copy-paste (and replace all) 250823 and 250824 contents into SteamVR folder. I did 250823 first.

And boom, SteamVR shows itself as 2.0.10.
I have no idea how stable it is, but it seems to work (I just ran Beat Saber and it looks fine)

Alternatives:
* https://github.com/SteamRE/DepotDownloader

**Comment by andy-d1969** [comment] 2023-11-18 16:16
Thank you very much. It works for now.

**Comment by aleiby** [comment] 2023-11-18 20:16
Can you try version 2.1.5 (in the beta branch of SteamVR) and see if that fixes the issue for you?  Thanks!

https://help.steampowered.com/en/faqs/view/4F5E-AD22-7402-2EAD

**Comment by LukeZaz** [comment] 2023-11-18 20:23
Haven't tested much, but 2.1.5 appears to fix this for me. SteamVR is showing up on the headset again and the error message no longer appears.

**Comment by caseif** [comment] 2023-11-18 20:33
Can confirm that 2.1.5 fixed the issue for me as well!

**Comment by Danielduel** [comment] 2023-11-18 22:13
I can confirm that the issue of 500 on startup is fixed in 2.1.5.
(I only launched SteamVR and checked if hmd works)

**Comment by Malthasa** [comment] 2023-11-18 22:13
Still doesnt work for me :(

**Comment by Danielduel** [comment] 2023-11-18 22:13
@Malthasa could you provide logs?

**Comment by Malthasa** [comment] 2023-11-18 23:34
How do i get my logs? I don't get the error anymore but i still only see a blackscreen on my headset

**Comment by Danielduel** [comment] 2023-11-19 15:16
3h session of Beat Saber 1.29.1 on 2.1.5 - no problems, I think current beta is stable for me.
@Malthasa https://github.com/ValveSoftware/SteamVR-for-Linux/blob/master/CapturingSystemReport.md

**Comment by NewtSoup** [comment] 2023-11-19 15:21
Steam VR 2.1.5 launches again for me.  Skyrim works pretty much as expected as do a few other games.  Fallout 4 VR though is still very below par.  The display graph is still a wall of magenta lines and the timing is 22ms/11.1 ms  Prior to  Steam VR 1.27 Falllout 4 was very playable and so this is my litmus test.

**Comment by alpnist** [comment] 2023-11-19 18:30
Same issue as Malthasa.  No errors but only black screen on the headset.  The vr view on the desktop shows that the headset is connected and being read by SteamVR.  The controllers are detected.  I am getting audio on the headset but no video.
https://gist.github.com/alpnist/a8b2d6c062a52e1692753779e5a0667b

**Comment by jnse** [comment] 2023-11-19 21:21
2.1.5 works for me as well, and the issue appears fixed for me anyway.

**Comment by alpnist** [comment] 2023-11-19 21:54
1.27.5 does work for me.  As 2.1.5 doesn't work for all of us, I'm adding to the requests that 2.0.10 be added to the betas.

**Comment by bobsdacool** [comment] 2023-11-20 19:39
using ALVR; black screen with audio on 2.1.5. 1.27.5 works for me, but I have to change to 2.1.5 then back to 1.27.5, give it a 540MB update, several restarts (of steamvr), re-register ALVR driver, then it works. Kind of cumbersome having to do this each reboot. Definitely think the last several versions of steamvr should be available under Beta.

**Comment by danieloneill** [comment] 2023-11-21 04:52
Using Stable: As described in initial report, Error 500, black screen.

Using Beta: Fedora reports that "vrwebhelper" crashed and ALVR doesn't detect SteamVR running, despite reinstalling driver, and SteamVR reports no headset being connected.

Also, though likely unrelated, SteamVR opens 3 settings windows; two of which are blank (empty), one of which has the actual settings. The other two cannot be closed, even when SteamVR and Steam are closed, without killing Xwayland server or rebooting PC/restarting session. I suspect this is a Wayland-specific (or Plasma specific) issue.

**Comment by andy-d1969** [comment] 2023-11-21 08:29
I can confirm that the error 500 issue is fixed by 2.1.5.

**Comment by KGOrphanides** [comment] 2023-11-21 16:23
Opting into the beta just now got me version 2.1.6, which also resolves the error 500 issue for me.

**Comment by danieloneill** [comment] 2023-11-21 19:13
2.1.6 removes the 500 error, and now gives a 108 error and no longer communicates with ALVR.

My current experience with the different version are as follows:
- None - Error 500 (SteamVR Fail)
- beta - No HMD/Controllers detected, fails to communicate with ALVR
- temp_v1.27.5 works

My experience with beta is as follows, as I spent a few hours trying to sort it.

It seems as though LD_LIBRARY_PATH no longer contains system paths in this beta, according to the vrserver environ contents:

```
LD_LIBRARY_PATH=/home/doneill/.local/share/Steam/steamapps/common/SteamVR:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/aliases:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/aliases:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64::/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64
```

and:

```
VRCOMPOSITOR_LD_LIBRARY_PATH=/home/doneill/.local/share/Steam/steamapps/common/SteamVR:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/qt/lib:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/aliases:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/aliases
```

For ALVR to work, it needs to load libavfilter.so.x (among others) which, on my system, is located in /lib64

SteamVR log indicates this issue with:
```
Unable to load driver alvr_server from /home/doneill/alvr/ALVR/build/alvr_streamer_linux/lib64/alvr/bin/linux64/driver_alvr_server.so (libavfilter.so.9: cannot open shared object file: No such file or directory)
ASSERT: "DriverManager alvr_server load error libavfilter.so.9: cannot open shared object file: No such file or directoryu" at /data/src/common/vrcommon/drivermanager.cpp:439.
Unable to load driver alvr_server because of error VRInitError_Init_FileNotFound(103). Skipping.
No connected devices found. Returning best error VRInitError_Init_HmdNotFound
```

I've attempted to symlink the libraries to "/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64" in my case, but with no success. I suspect it's simply that the dependencies of libav* are just too complex, but I also noticed via strace that one (or more) SteamVR processes are mmaping libavfilter.so.7, where my ALVR build is using libavfilter.so.9.

Suspecting a version/symbol issue, I tried rebuilding ALVR against the same versions. This doesn't change the result, however, besides the error message changing to "libavfilter.so.7: cannot open shared object file".

The environment of temp_v1.27.5 (which works) retains the system library paths as follows:
```
LD_LIBRARY_PATH=/home/doneill/.local/share/Steam/steamapps/common/SteamVR:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/qt/lib:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/local/cuda-12.2/targets/x86_64-linux/lib:/usr/lib64/iscsi:/usr/lib64/llvm15/lib:/usr/local/lib64:/usr/i686-w64-mingw32/lib:/usr/x86_64-w64-mingw32/lib:/usr/lib64/pipewire-0.3/jack:/usr/lib64/tcl8.6:/lib:/lib64:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/lib:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib:/home/doneill/.local/share/Steam/steamapps/common/SteamVR:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64
```

and

```
VRCOMPOSITOR_LD_LIBRARY_PATH=/home/doneill/.local/share/Steam/steamapps/common/SteamVR:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/qt/lib:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/local/cuda-12.2/targets/x86_64-linux/lib:/usr/lib64/iscsi:/usr/lib64/llvm15/lib:/usr/local/lib64:/usr/i686-w64-mingw32/lib:/usr/x86_64-w64-mingw32/lib:/usr/lib64/pipewire-0.3/jack:/usr/lib64/tcl8.6:/lib:/lib64:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/lib:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib:/home/doneill/.local/share/Steam/steamapps/common/SteamVR
```

While the gap in versions is large enough that all my detective work could just be looking at an unrelated red herring, I hope some of it helps.

**Comment by alpnist** [comment] 2023-11-22 03:49
2.1.7 black screen on the Quest 2.  No improvement.  Still hoping for 2.0.10 to be made available as a beta.

**Comment by andy-d1969** [comment] 2023-11-22 12:10
To get ALVR to work with SteamVR 2.1.5 or higher, I had to start SteamVR with Steam-Play-None. https://github.com/Scrumplex/Steam-Play-None

**Comment by Danielduel** [comment] 2023-11-22 14:23
To incerase reach of ALVR-connected problems on latest steamvr - I suggest creating a new issue with title clearly stating that it is a problem.
@andy-d1969

**Comment by alpnist** [comment] 2023-11-22 19:49
Steam Play None did fix the black screen issue on the headset, so the latest 2.1 is working.  Using ALVR (as would most or all Quest users on Linux)  Posting here so other people with the problem can find the fix.

**Comment by AnOpenSauceDev** [comment] 2023-11-22 20:25
Relevant issue on Steam Beta Client: https://github.com/alvr-org/ALVR/pull/1845

**Comment by MaKraMc** [comment] 2023-11-24 20:51
Steamvr 2.1.7 works for me again :)

**Comment by shfbsdbvf** [comment] 2023-11-26 12:49
I also have this issue :(
**System Information:**
- Distribution: Gentoo
- SteamVR version: 2.1.4
- Steam client version: 1700160213
- Opted into Steam client beta?: No
- Graphics driver version:  Mesa 23.1.8
- Gist for SteamVR System Information: https://gist.github.com/shfbsdbvf/edfd56d41d2f6a36b5236a471f90a165

Switching to beta doesn't solve the issue, gives me "Something is wrong. A key component of SteamVR isn't working correctly. Please reinstall SteamVR. (303)" error instead.
**System Information:**
- Distribution: Gentoo
- SteamVR version: 2.1.7
- Steam client version: 1700160213
- Opted into Steam client beta?: No
- Graphics driver version:  Mesa 23.1.8
- Gist for SteamVR System Information: https://gist.github.com/shfbsdbvf/344b4b5cf06bf735b38b730311ad190e

**Comment by leetus** [comment] 2023-11-26 23:07
> 2.1.6 removes the 500 error, and now gives a 108 error and no longer communicates with ALVR.
> 
> My current experience with the different version are as follows:
> 
>     * None - Error 500 (SteamVR Fail)
> 
>     * beta - No HMD/Controllers detected, fails to communicate with ALVR
> 
>     * temp_v1.27.5 works
> 
> 
> My experience with beta is as follows, as I spent a few hours trying to sort it.
> 
> It seems as though LD_LIBRARY_PATH no longer contains system paths in this beta, according to the vrserver environ contents:
> 
> ```
> LD_LIBRARY_PATH=/home/doneill/.local/share/Steam/steamapps/common/SteamVR:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/aliases:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/aliases:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64::/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64
> ```
> 
> and:
> 
> ```
> VRCOMPOSITOR_LD_LIBRARY_PATH=/home/doneill/.local/share/Steam/steamapps/common/SteamVR:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/qt/lib:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/aliases:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/aliases
> ```
> 
> For ALVR to work, it needs to load libavfilter.so.x (among others) which, on my system, is located in /lib64
> 
> SteamVR log indicates this issue with:
> 
> ```
> Unable to load driver alvr_server from /home/doneill/alvr/ALVR/build/alvr_streamer_linux/lib64/alvr/bin/linux64/driver_alvr_server.so (libavfilter.so.9: cannot open shared object file: No such file or directory)
> ASSERT: "DriverManager alvr_server load error libavfilter.so.9: cannot open shared object file: No such file or directoryu" at /data/src/common/vrcommon/drivermanager.cpp:439.
> Unable to load driver alvr_server because of error VRInitError_Init_FileNotFound(103). Skipping.
> No connected devices found. Returning best error VRInitError_Init_HmdNotFound
> ```
> 
> I've attempted to symlink the libraries to "/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64" in my case, but with no success. I suspect it's simply that the dependencies of libav* are just too complex, but I also noticed via strace that one (or more) SteamVR processes are mmaping libavfilter.so.7, where my ALVR build is using libavfilter.so.9.
> 
> Suspecting a version/symbol issue, I tried rebuilding ALVR against the same versions. This doesn't change the result, however, besides the error message changing to "libavfilter.so.7: cannot open shared object file".
> 
> The environment of temp_v1.27.5 (which works) retains the system library paths as follows:
> 
> ```
> LD_LIBRARY_PATH=/home/doneill/.local/share/Steam/steamapps/common/SteamVR:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/qt/lib:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/local/cuda-12.2/targets/x86_64-linux/lib:/usr/lib64/iscsi:/usr/lib64/llvm15/lib:/usr/local/lib64:/usr/i686-w64-mingw32/lib:/usr/x86_64-w64-mingw32/lib:/usr/lib64/pipewire-0.3/jack:/usr/lib64/tcl8.6:/lib:/lib64:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/lib:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib:/home/doneill/.local/share/Steam/steamapps/common/SteamVR:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64
> ```
> 
> and
> 
> ```
> VRCOMPOSITOR_LD_LIBRARY_PATH=/home/doneill/.local/share/Steam/steamapps/common/SteamVR:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/qt/lib:/home/doneill/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/local/cuda-12.2/targets/x86_64-linux/lib:/usr/lib64/iscsi:/usr/lib64/llvm15/lib:/usr/local/lib64:/usr/i686-w64-mingw32/lib:/usr/x86_64-w64-mingw32/lib:/usr/lib64/pipewire-0.3/jack:/usr/lib64/tcl8.6:/lib:/lib64:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/lib:/home/doneill/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib:/home/doneill/.local/share/Steam/steamapps/common/SteamVR
> ```
> 
> While the gap in versions is large enough that all my detective work could just be looking at an unrelated red herring, I hope some of it helps.

Fix works on KDE/Kubuntu.

**Comment by Dreamurrrr** [comment] 2023-11-28 21:35
I still have this issue. Had to use the steamcmd workaround to get it working. Currently on Linux Mint 19.3 with Nvidia 535 installed.

**Comment by ernstp** [comment] 2023-11-30 05:42
This seems to be solved for me with the 2.1.8 Hotfix (Nov 30). Ubuntu 23.10, Radeon, HTV Vive.

**Comment by icychkn** [comment] 2023-11-30 17:33
OS: Artix Linux (64 bit)
Kernel Version: 6.6.2-artix1-1
Steam Beta: Yes
SteamVR: 2.1.8
Headset: Valve Index
AMD Driver: AMD AMD Radeon RX 6700 XT (navi22, LLVM 16.0.6, DRM 3.54, 6.6.2-artix1-1)
AMD Driver Version: 4.6 (Compatibility Profile) Mesa 23.2.1-arch1.2

Can confirm it works properly with 2.1.8.

**Comment by Danielduel** [comment] 2023-11-30 18:03
Hi @kisak-valve 
Would you like a bit more polished version of https://github.com/ValveSoftware/SteamVR-for-Linux/issues/639#issuecomment-1817538299 as a `DowngradingStableVersion.md` guide in the repository root?

**Comment by flying-sheep** [comment] 2023-11-30 18:37
> Can confirm it works properly with 2.1.8.

not for me.

**Comment by ThaSwapMeetPimp** [comment] 2023-12-02 05:58
This has been fixed for me for a hot minute. Had some pretty heavy stuff going on, so havent had time to say it. Would close but apparently others are still having the issue.

**Comment by shfbsdbvf** [comment] 2023-12-02 13:10
Works in SteamVR 2.1.8 :)

**Comment by kisak-valve** [comment] 2023-12-02 13:57
Closing as fixed.

Follow up issues should be tracked separately.

**Closed by kisak-valve** 2023-12-02 13:57 UTC
Labels: bug, Need Retest
