### ISSUE TITLE
Regression with 1.8.2 Beta + Valve Index, SteamVR Fail (306)

### ISSUE THREAD

**Issue by rstrube** [ValveSoftware/SteamVR-for-Linux#247] opened 2019-09-18 00:44 UTC
**Describe the bug**
After updating to SteamVR 1.8.2 Beta, I always see the following upon starting up SteamVR:

![image](https://user-images.githubusercontent.com/4212764/65094639-0c2d2200-d97b-11e9-8efe-9a84a8c71bec.png)

In addition, it's worth noting that for 5-10 seconds the mouse cursor is unresponsive / very slow on my Gnome DE after starting Steam VR.

This behavior does not exist in the 1.7 stable version or the 1.8.1 Beta version of SteamVR

**To Reproduce**
1. Install the latest SteamVR Beta 1.8.2
2. Start SteamVR

**Expected behavior**
SteamVR should start normally

**System Information (please complete the following information):**
- Distribution: Ubuntu 19.04
- SteamVR version: 1.8.2 Beta
- Steam client version: September 17, 2019 
- Opted into Steam client beta?: Yes
- Graphics driver version:  Nvidia Driver 435.21
- Gist for SteamVR System Information: https://gist.github.com/rstrube/6567019bb467c81dc3b445bca2190380

**Comment by SlickMcRunFast** [comment] 2019-09-18 02:02
Same issue and same system info for me
https://gist.github.com/SlickMcRunFast/21bee587d454f8ad5d7d9a43cd268b93

**Comment by Zamundaaa** [comment] 2019-09-18 10:15
Manjaro KDE, kernel 5.3.0 + Mesa 19.3.0-devel (git-f812cbfd88) (LLVM 10.0.0) here, no such issue.
Looks like a NVidia issue to me.

**Comment by jrtberlin** [comment] 2019-09-18 11:33
Same issue with KDE neon (based on Ubuntu 18.04.1) since the latest beta release: 

SteamVR Version:	1.8.2 (1568754983)
SteamVR Date:	2019-09-17
Steam Branch:	beta
OS:	Linux version 5.2.11-steamvr-generic
NVIDIA Driver Version: 435.21

https://gist.github.com/jrtberlin/9f260bc0a659be6ca5081e300f2ac36c

**Comment by Vash63** [comment] 2019-09-18 11:55
I'm also getting this. The SteamVR system report seems to be missing the crash, when I review my system logs I'm seeing the initial crash is in libnvidia-glcore but this is missing from the SteamVR System Report: 
```
audit[4914]: ANOM_ABEND auid=1000 uid=1000 gid=100 ses=2 pid=4914 comm="VulkanVblankThr" exe="/home/vash/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor" sig=11 res=1
steam.desktop[1600]: crash_20190918132109_1.dmp[4975]: Uploading dump (out-of-process)
steam.desktop[1600]: /tmp/dumps/crash_20190918132109_1.dmp
crash_20190918132109_1.dmp[4975]: Uploading dump (out-of-process)
                                  /tmp/dumps/crash_20190918132109_1.dmp
kernel: VulkanVblankThr[4933]: segfault at 0 ip 00007efbf90eecdd sp 00007efbf2f85cf0 error 4 in libnvidia-glcore.so.435.19.03[7efbf82b0000+12bc000]
kernel: Code: 89 c5 53 74 67 48 8b 05 f9 fe e6 00 4d 63 e8 4a 8d 3c ed 00 00 00 00 ff 10 85 ed 48 89 c3 7e 24 31 c9 31 d2 49 8b 04 d4 ff c1 <8b> 00 66 c7 44 d3 04 03 00 66 c7 44 d3 06 00 00 89 04 d3 48 ff c2
kernel: audit: type=1701 audit(1568805670.088:62): auid=1000 uid=1000 gid=100 ses=2 pid=4914 comm="VulkanVblankThr" exe="/home/vash/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor" sig=11 res=1 
```
[steamvr1.8.2.VulkanVblankThr.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/3626218/steamvr1.8.2.VulkanVblankThr.txt)
[SteamVR-2019-09-18-PM_01_50_10.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/3626219/SteamVR-2019-09-18-PM_01_50_10.txt)

Also worth noting is that the symptoms are far worse than I have gsync enabled. Disabling gsync via `nvidia-settings -a CurrentMetaMode="DPY-3: 2560x1440_144 @2560x1440 +0+0 {ViewPortIn=2560x1440, ViewPortOut=2560x1440+0+0, AllowGSYNC=off}"` improves the situation from locking up X11 and crashing even the SteamVR desktop dashboard to just crashing the vrcompositor (so I could still generate a system report).

**Comment by Darkheron** [comment] 2019-09-18 14:36
Same.. repost from patch discussion on the steam forums.

No longer functional on Ubuntu 18.04.3. Receive an error 306. The monitor comes up and shows the connected devices, but it doesn't look like the compositor is starting. Vr_Init seems to be failing, even though the error returned from the call is vr::VRInitError_None

Here's what seems to be the error text:
Tue Sep 17 2019 19:48:33.729653 - godot.x11.tools.64 1.8.2 startup with PID=5792, config=/home/darkheron/.local/share/Steam/config, runtime=/home/darkheron/.local/share/Steam/steamapps/common/SteamVR
Tue Sep 17 2019 19:48:33.729699 - vrclient type=VRApplication_Scene
Tue Sep 17 2019 19:48:33.730288 - [Settings] Load Default Json Settings from /home/darkheron/.local/share/Steam/steamapps/common/SteamVR/drivers/htc/resources/settings/default.vrsettings
Tue Sep 17 2019 19:48:33.730350 - [Settings] Load Default Json Settings from /home/darkheron/.local/share/Steam/steamapps/common/SteamVR/drivers/lighthouse/resources/settings/default.vrsettings
Tue Sep 17 2019 19:48:33.730396 - [Settings] Load Default Json Settings from /home/darkheron/.local/share/Steam/steamapps/common/SteamVR/drivers/null/resources/settings/default.vrsettings
Tue Sep 17 2019 19:48:33.730547 - [Settings] Load Default Json Settings from /home/darkheron/.local/share/Steam/steamapps/common/SteamVR/resources/settings/default.vrsettings
Tue Sep 17 2019 19:48:33.730933 - [Settings] Load Json Settings from /home/darkheron/.local/share/Steam/config/steamvr.vrsettings
Tue Sep 17 2019 19:48:33.913145 - CIPCPipe::ConnectPipe(SteamVR_Namespace) attempting connect to steamvr:SteamVR_Namespace
Tue Sep 17 2019 19:48:33.913257 - CSharedResourceNamespaceClient::Init(): received namespace data 4610
Tue Sep 17 2019 19:48:33.913289 - CIPCPipe::ConnectPipe(VR_ServerPipe_4610) attempting connect to steamvr:VR_ServerPipe_4610
Tue Sep 17 2019 19:48:33.915604 - Received success response from vrserver connect
Tue Sep 17 2019 19:48:33.916850 - Not looking for a good app key because Steam didn't start this app
Tue Sep 17 2019 19:48:33.916873 - App key after connect message:system.generated.godot.x11.tools.64
Tue Sep 17 2019 19:48:33.921530 - CIPCPipe::ConnectPipe(VR_CompositorPipe_4610) attempting connect to steamvr:VR_CompositorPipe_4610
Tue Sep 17 2019 19:48:33.921553 - Unable to connect to pipe errno=111
Tue Sep 17 2019 19:48:33.932368 - Starting vrcompositor process: /home/darkheron/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor-launcher 
Using vrcompositor capability proxy
Launching /home/darkheron/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor
Using breakpad crash handler
Setting breakpad minidump AppID = 250820
Forcing breakpad minidump interfaces to load
Tue Sep 17 2019 19:48:33.944276 - CIPCPipe::ConnectPipe(VR_CompositorPipe_4610) attempting connect to steamvr:VR_CompositorPipe_4610
Tue Sep 17 2019 19:48:33.944325 - Unable to connect to pipe errno=111
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Tue Sep 17 2019 19:48:34.044468 - CIPCPipe::ConnectPipe(VR_CompositorPipe_4610) attempting connect to steamvr:VR_CompositorPipe_4610
Tue Sep 17 2019 19:48:34.044527 - Unable to connect to pipe errno=111
Tue Sep 17 2019 19:48:34.144654 - CIPCPipe::ConnectPipe(VR_CompositorPipe_4610) attempting connect to steamvr:VR_CompositorPipe_4610
Tue Sep 17 2019 19:48:34.144704 - Unable to connect to pipe errno=111
Tue Sep 17 2019 19:48:34.244836 - CIPCPipe::ConnectPipe(VR_CompositorPipe_4610) attempting connect to steamvr:VR_CompositorPipe_4610

is the errno 111 here the standard linux error for connection refused? Did needed permissions change somehow? Worked really well until this patch.

I can provide more information and dig around if necessary, but this is all I have time for today.

**Comment by lostgoat** [comment] 2019-09-18 17:19
Hey Everyone,

Thanks for reporting this issue. As far as I can tell we have two separate crashes here.

Crash #1 is from users who have `Failed Watchdog timeout in thread Render in Update after 5.806722 seconds. Aborting.` in their system reports. This hang is 1.8.2 specific and reverting back to 1.8.1 should be a temporary workaround.

Crash #2 is in `VulkanBlankThread`. This is due to an Nvidia driver regression in their beta drivers. Moving to a non-beta driver branch should help resolve this issue.

If neither of the above works for you let me know.

**Comment by rstrube** [comment] 2019-09-18 17:32
> Crash # 2 is in `VulkanBlankThread`. This is due to an Nvidia driver regression in their beta drivers. Moving to a non-beta driver branch should help resolve this issue.

Thank you for your reply.  I do want to clarify that the Nvidia **435.21** driver is not the beta driver, it's the latest "short lived branch" stable driver.

https://www.nvidia.com/en-us/drivers/unix/

Either way, it sounds like it's a nvidia driver bug...

**Comment by rstrube** [comment] 2019-09-18 17:40
> I'm also getting this. The SteamVR system report seems to be missing the crash, when I review my system logs I'm seeing the initial crash is in libnvidia-glcore but this is missing from the SteamVR System Report:
> 
> ```
> audit[4914]: ANOM_ABEND auid=1000 uid=1000 gid=100 ses=2 pid=4914 comm="VulkanVblankThr" exe="/home/vash/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor" sig=11 res=1
> steam.desktop[1600]: crash_20190918132109_1.dmp[4975]: Uploading dump (out-of-process)
> steam.desktop[1600]: /tmp/dumps/crash_20190918132109_1.dmp
> crash_20190918132109_1.dmp[4975]: Uploading dump (out-of-process)
>                                   /tmp/dumps/crash_20190918132109_1.dmp
> kernel: VulkanVblankThr[4933]: segfault at 0 ip 00007efbf90eecdd sp 00007efbf2f85cf0 error 4 in libnvidia-glcore.so.435.19.03[7efbf82b0000+12bc000]
> kernel: Code: 89 c5 53 74 67 48 8b 05 f9 fe e6 00 4d 63 e8 4a 8d 3c ed 00 00 00 00 ff 10 85 ed 48 89 c3 7e 24 31 c9 31 d2 49 8b 04 d4 ff c1 <8b> 00 66 c7 44 d3 04 03 00 66 c7 44 d3 06 00 00 89 04 d3 48 ff c2
> kernel: audit: type=1701 audit(1568805670.088:62): auid=1000 uid=1000 gid=100 ses=2 pid=4914 comm="VulkanVblankThr" exe="/home/vash/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor" sig=11 res=1 
> ```
> 
> [steamvr1.8.2.VulkanVblankThr.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/3626218/steamvr1.8.2.VulkanVblankThr.txt)
> [SteamVR-2019-09-18-PM_01_50_10.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/3626219/SteamVR-2019-09-18-PM_01_50_10.txt)
> 
> Also worth noting is that the symptoms are far worse than I have gsync enabled. Disabling gsync via `nvidia-settings -a CurrentMetaMode="DPY-3: 2560x1440_144 @2560x1440 +0+0 {ViewPortIn=2560x1440, ViewPortOut=2560x1440+0+0, AllowGSYNC=off}"` improves the situation from locking up X11 and crashing even the SteamVR desktop dashboard to just crashing the vrcompositor (so I could still generate a system report).

Can you clarify what Nvidia driver version your running?

**Comment by Vash63** [comment] 2019-09-18 18:45
I'm running 435.19.03, but I got a reply from Nvidia that it should be fixed in the newly released 435.24.02. I'll test this when back at my PC if no one else here has gotten a chance.

**Comment by rstrube** [comment] 2019-09-18 18:48
> I'm running 435.19.03, but I got a reply from Nvidia that it should be fixed in the newly released 435.24.02. I'll test this when back at my PC if no one else here has gotten a chance.

Thank you, I see the confusion now, I conflated the two issues, but Crash #2 (your crash) is an independent problem.

**Comment by Vash63** [comment] 2019-09-19 00:37
New Nvidia drivers 435.24.02 did fix my previous crash in VulkanVblankThr, but it's still crashing. I can no longer generate a full system report but here is the vrcompositor.txt log: 
[vrcompositor.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/3628840/vrcompositor.txt)

**Comment by h1z1** [comment] 2019-09-19 22:38
Can confirm the same.

```
[70878.662550] nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000927c:1:0:830
[70880.662949] nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000927c:1:0:830
[70882.722677] nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000927c:1:0:830
[70884.723482] nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000927c:1:0:830
```

```
Thu Sep 19 2019 17:36:13.417977 - Failed Watchdog timeout in thread Render in Up
date after 5.894147 seconds. Aborting.
```
```
# cat /proc/driver/nvidia/version 
NVRM version: NVIDIA UNIX x86_64 Kernel Module  435.21  Sun Aug 25 08:17:57 CDT 2019
GCC version:  gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
```

Latest stable [435.21](https://www.nvidia.com/content/DriverDownload-March2009/confirmation.php?url=/XFree86/Linux-x86_64/435.21/NVIDIA-Linux-x86_64-435.21.run&lang=us&type=TITAN)  doesn't have crash 2 but 1 still remains. 

Latest Vulkan Beta release today [435.24.02](https://developer.nvidia.com/vulkan-beta-4352402-linux) doesn't have crash 2 but 1 still remains. 


 Interesting thing is NVIDIA considers 2 seconds to be an error condition while Steam waits 5.  Not sure how that effects actual state between them. 

Either way both of these are ultimately NVIDIA problems.  Steam shouldn't be able to hang a GPU.

**Comment by fabiankranewitter** [comment] 2019-09-21 12:39
I get almost the same error with the beta of steam vr (1.8.5). Only with me the error is no longer 306 but 307. Everything is running normally on the stable version.

![steamvr](https://user-images.githubusercontent.com/6630450/65373331-63353e80-dc7c-11e9-8ab6-09654cd81508.png)
```
dmesg output:
[12300.213722] nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000927c:2:0:830
[12302.214347] nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000927c:2:0:830
[12310.244155] nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000927c:2:0:830
[12312.244612] nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000927c:2:0:830
[12314.393243] nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000927c:2:0:830
[12316.394122] nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000927c:2:0:830
[12319.648691] show_signal_msg: 53 callbacks suppressed
[12319.648693] Web Thread[7210]: segfault at 0 ip 00000000006115b4 sp 00007fa5acd05c40 error 4 in vrserver[400000+406000]

```
```
cat /proc/driver/nvidia/version 
NVRM version: NVIDIA UNIX x86_64 Kernel Module  435.21  Sun Aug 25 08:17:57 CDT 2019
GCC version:  gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1) 
```

**Comment by mimattr** [comment] 2019-09-21 14:01
Can confirm the same **SteamVR** launch issue as @fabiankranewitter, @h1z1 and @Vash63:
```
14:11:46 kernel: nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000c57e:2:0:830
14:11:46 kernel: nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000c57e:2:0:830
14:11:44 kernel: nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000c57e:2:0:830
14:11:42 kernel: nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000c57e:2:0:830
14:11:40 kernel: nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000c57e:2:0:830
14:10:13 kernel: nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000c57e:2:0:830
14:10:11 kernel: nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000c57e:2:0:830
14:10:09 kernel: nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000c57e:2:0:830
14:10:07 kernel: nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000c57e:2:0:830
14:09:31 kernel: nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000c57e:2:0:830
14:09:29 kernel: nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000c57e:2:0:830
14:09:27 kernel: nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000c57e:2:0:830
14:09:25 kernel: nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000c57e:2:0:830
14:08:59 kernel: nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000c57e:2:0:830
14:08:57 kernel: nvidia-modeset: ERROR: GPU:0: Idling display engine timed out: 0x0000c57e:2:0:830
```

## System Information
- GPU: **RTX 2060**
- Driver/LLVM version: **NVIDIA 435.21**
- Kernel version: **5.0.0-29-generic**
- [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
- Proton version: **4.11-5**
- SteamVR version: **1.8.5**

## I confirm:
- [x] that I have checked whether there are updates for my system available.

[SteamVR System Report](https://gist.github.com/mimattr/9dd30e7e72dd953b8289eca9a66e31a9)
[vrcompositor.txt](https://gist.github.com/mimattr/a52c29e7caef68f9984ca7b68d88e034)

## Reproduction
1. Select the `SteamVR` icon within the Steam client (top-right)

**Comment by lostgoat** [comment] 2019-09-26 14:23
A fix for this issue has been pushed out with SteamVR Beta 1.8.6

**Closed by lostgoat** 2019-09-26 14:23 UTC
Labels: bug

**Comment by rstrube** [comment] 2019-09-27 14:59
I can confirm that 1.8.6 resolved this problem, thanks!
