### ISSUE TITLE
[BUG] Failed to allocate new VRCompositor semaphore

### ISSUE THREAD

**Issue by maxaudron** [ValveSoftware/SteamVR-for-Linux#252] opened 2019-09-24 14:39 UTC
**Describe the bug**
When starting SteamVR the computer begins to hang until a generic steamvr fail error message pops up. Upon investigating the logs i could trace it back to vrclient_vrwebhelper_main:

```
Tue Sep 24 2019 14:18:12.290802 - Failed to allocate new VRCompositor semaphore
Tue Sep 24 2019 14:18:12.290811 - Failed to create shared vulkan semaphore
Tue Sep 24 2019 14:18:12.290824 - Initializing CVulkanVRRenderer
Tue Sep 24 2019 14:18:12.290850 - Debug markers: disabled, missing extension support. Is the Renderdoc layer enabled?
Tue Sep 24 2019 14:18:12.322125 - Initialized Vulkan transfer ring buffer, mapped at offset 0x0x7fdbb2a3d000.
Tue Sep 24 2019 14:18:12.322808 - Failed to allocate new VRCompositor semaphore
Tue Sep 24 2019 14:18:12.322823 - Failed to create shared vulkan semaphore
Tue Sep 24 2019 14:18:12.322835 - CSharedResourceBaseLinux::CreateAssociatedResources failed to pre-allocate semaphore handle=0x10000204d slot=0
Tue Sep 24 2019 14:18:12.322842 - SharedCountingSemaphoreLinux::CreateVulkanCountingSemaphore: failed to create associated semaphores.
Tue Sep 24 2019 14:18:12.322857 - CVulkanVRRenderer::CreateGPUCountingSemaphore - Failed to allocate counting shared resource
```
Full Logs:
[vrclient_vrwebhelper_main.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/3647742/vrclient_vrwebhelper_main.txt)

**System Information (please complete the following information):**
- Distribution: Fedora 30
- VR Headset: Valve Index
- SteamVR version: 1.8.5
- Steam client version: Sep 23 2019, at 16:07:56 / 1569270763
- Opted into Steam client beta?: Yes
- Graphics driver version:  Nvidia 435.21
- Gist for SteamVR System Information: https://gist.github.com/maxaudron/1c07abce5ddfde80c1bf3e0921328d86

**Comment by lostgoat** [comment] 2019-09-24 15:24
Hi @maxaudron 

Thanks for the report. This looks like a duplicate of #247 

I'm closing it for now, but feel free to re-open it once the fix for #247 ships if you still experience this problem.

**Closed by lostgoat** 2019-09-24 15:24 UTC
Labels: bug
