### ISSUE TITLE
Room setup hangs on Mint

### ISSUE THREAD

**Issue by Boyfinn** [ValveSoftware/SteamVR-for-Linux#700] opened 2024-05-11 18:27 UTC
**Describe the bug**
When trying to start the room setup in SteamVR, the program's desktop window displays "Waiting...". Looking through the headset, both the headset and controllers track just fine. The default SteamVR environment shows a hovering window that indicates the next application (Room setup) is starting with the text "Next up: Room setup" under the room setup application banner. All tracking and controllers still work, and I can access the VR escape menu, but returning back to the game (Room setup) just brings back up the previously mentioned application banner with the text "Next up".
Trying to enable the "Display VR view" setting at this point produces a blank window, even though the headset outputs video and tracks just fine. Sometimes bringing up this view up produces a black unkillable window.

**To Reproduce**
1. Plug in your headset & base stations & turn on your controllers.
2. Once all hardware shows up in SteamVR, start the Room Setup
3. SteamVR gets stuck.

**Expected behavior**
Room setup to start, or for errors to be produced in logs.

**System Information (please complete the following information):**
Steam client version: 1714854927
SteamVR version: beta 2.6.1

Linux Distribution info:
Distribution: Linux Mint 21.3
Kernel build: 6.5.0-1022
Desktop&Windowing: Cinnamon 6.0.4 over X11

SteamVR report & logs:
[SteamVR-2024-05-11-PM_09_11_38.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/15283959/SteamVR-2024-05-11-PM_09_11_38.txt)

**Comment by TTimo** [comment] 2024-05-14 17:19
Duplicate of https://github.com/ValveSoftware/SteamVR-for-Linux/issues/694, see there for a workaround.

**Closed as completed by TTimo** 2024-05-14 17:19 UTC
Labels: bug
