### ISSUE TITLE
Steam Runtime creates import error for OpenCV in Python

### ISSUE THREAD

**Issue by naveenT1010** [ValveSoftware/SteamVR-for-Linux#62] opened 2017-06-29 16:42 UTC
#### Your system information
* Steam client version: Jun 16 2017
* Distribution: Ubuntu 16.04 
* Graphics driver version: 381.22
* Gist for SteamVR System Information: [System Report](https://gist.github.com/naveenT1010/f483316a3dd4e6db89cba3da142f60e5)
* Opted into Steam client beta?:Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When I try to run Unreal Engine with steamVR runtime, and I import OpenCV with Python in there, I get import error:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/lib/x86_64-linux-gnu/libhogweed.so.4: undefined symbol: __gmpn_cnd_sub_n
```
I dont get this error if I am not using steam runtime.

#### Steps for reproducing this issue:
The simplest way to reproduce this error without Unreal Engine is
1.  run python with steamVR runtime:
```bash
$ .steam/steam/ubuntu12_32/steam-runtime/run.sh python
```
2. And then try to import cv2 (OpenCV library)
```python
import cv2
```

**Comment by kisak-valve** [comment] 2017-06-29 17:19
Closing as a duplicate of https://github.com/ValveSoftware/steam-runtime/issues/73.

**Closed by kisak-valve** 2017-06-29 17:19 UTC
