### ISSUE TITLE
[BUG] Steamvr 2.0+ interface gone.

### ISSUE THREAD

**Issue by Ehkad** [ValveSoftware/SteamVR-for-Linux#744] opened 2024-10-11 11:53 UTC
**Describe the bug**
When calling the steamvr ui it prevents the old UI.

**To Reproduce**
1. Have steam beta client installed.
2. Install steamvr.
3. Run steamvr.
4. Press menu button.
5. See old UI rather than new UI.

**Expected behavior**
Display steamvr's new ui

**System Information (please complete the following information):**
Please use the latest Steam beta client and SteamVR beta for your bug reports!

* Steam client version (build number or date):1728606687
* SteamVR version: 2.85
* Distribution (e.g. Ubuntu): Arch

**Additional context**
Works fine without steam beta client on steamvr beta 2.85.
Started after beta client that "fixed" Steamvr Failed to initialize: VR API not loaded (101)

**Comment by Corben78** [comment] 2024-10-12 08:31
Same here. Steam Client Beta causes the old Steam VR UI to start up.
Independent of Steam VR stable or beta. I'm on Ubuntu 22.04 and nVidia with 560 drivers.

Steam Client stable:

![image](https://github.com/user-attachments/assets/98fdd789-4471-42c6-9776-4396a4f2e05e)

Steam Client beta:

![image](https://github.com/user-attachments/assets/8044d3af-105a-4267-a415-7e2b3d1f020f)

System Report: 
[SteamVR-2024-10-12-AM_10_19_57.txt](https://github.com/user-attachments/files/17349351/SteamVR-2024-10-12-AM_10_19_57.txt)

**Comment by Patola** [comment] 2024-10-12 08:49
I've just made the test, in regular Steam started SteamVR stable, it's the 2.0 interface; changed to the Steam beta, started SteamVR stable again, it's the 1.0 interface; changed to Steam stable again, started SteamVR stable again, got the 2.0 interface.

So it's another confirmation. Happens to me too, my setup is here (arch, RX 7900 XTX, Valve Index): https://gist.github.com/Patola/5e7a97c495bb201a73ec5e32408c83aa

**Comment by KingVulpes** [comment] 2024-10-14 15:22
I'm having the same issue on Steam Deck but both the release and beta are broken

**Comment by KingVulpes** [comment] 2024-10-14 20:18
> I'm having the same issue on Steam Deck but both the release and beta are broken

Just confirmed it's SteamOS issue

**Comment by meir** [comment] 2024-11-07 17:11
Getting this issue on the non-beta steam version aswell now, not sure how to fix this

**Comment by szneqz** [comment] 2024-11-07 17:44
Yeah, the same problem for me. Additionally my games now crash steam.

**Comment by Entrix22** [comment] 2024-11-07 21:22
I updated my system yesterday and it started happening. I was on steam stable and steam vr stable. Also doesn't matter what steam vr version you use. So its a bug with steam itself.

**Comment by KingVulpes** [comment] 2024-11-07 22:13
> I updated my system yesterday and it started happening. I was on steam stable and steam vr stable. Also doesn't matter what steam vr version you use. So its a bug with steam itself.

I've been having this issue on Steam Deck for awhile

**Comment by jeremyselan** [comment] 2024-11-09 01:00
This should be fixed in the latest Steam Client Beta. (note that you must manually opt into this in the Steam Settings).  Let us know if you see otherwise? https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/4489619632029696079

**Comment by kisak-valve** [comment] 2024-11-09 02:35
Hello @jeremyselan, friendly note that I altered your link to a variant that does not require authentication to view.

**Comment by wallcarpet40** [comment] 2024-11-10 10:41
Looks like the latest Steam client Beta-version fixes this issue for me. Fedora 41, KDE Plasma 6.2.3 Wayland.

**Comment by Ehkad** [comment] 2024-11-12 16:20
Just tested as well. Fixed for me on Arch with latest beta client.

**Comment by KingVulpes** [comment] 2024-11-12 16:23
Can confirm, updating the Steam Deck to Beta client fixed everything

**Closed as completed** 2024-11-13 13:33 UTC
Labels: bug
