### ISSUE TITLE
[BUG] "Shared IPC Compositor Init Failed (303)"

### ISSUE THREAD

**Issue by yshui** [ValveSoftware/SteamVR-for-Linux#572] opened 2023-03-31 07:28 UTC
**Describe the bug**
During the startup of SteamVR, a popup shows up and gives me this error message. However, SteamVR seems to function normally despite this error.

**To Reproduce**
1. Start SteamVR

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: 1.26.1
- Steam client version: Mar 20 2023, at 22:21:44
- Opted into Steam client beta?: Yes
- Graphics driver version:  Mesa 23.0.1

**Comment by farmboy0** [comment] 2023-03-31 09:53
It doesnt work completely, SteamVR is not able to connect to steam and show the list of VR games.

**Comment by apcolvin** [comment] 2023-03-31 10:34
I am also seeing this error using opensuse but for me Home will not start either

**Comment by yaomtc** [comment] 2023-04-01 02:04
Glad to know it's not just me. Doesn't work either in X11 nor Wayland (using Mesa with RX 5700 XT).

Not only do I get the error, though, it also causes my screen to freeze up and sometimes kills the session, sending me back to SDDM... that or I have to switch to another TTY.

**Comment by Runlevel-zero** [comment] 2023-04-01 07:52
1.26.1 gives me the same compositor failure but I actually get a tremendous boost in native openXR applications. The compositor that crashed seems like it was bugged and causing wierd jitter when it was working either directly or indirectly.
 
I am on an Index (must use steamVR for openXR implementations) on Manjaro, full AMD, kernel 6.1.

FYI Steam forum thread on same subject, advice there was to revert off of the beta release: https://steamcommunity.com/app/250820/discussions/3/5796736234839613317/

@yaomtc this was introduced in yesterdays beta patch afaik, if you have been troubleshooting longer than that it's likely a different issue sadly.

**Comment by yaomtc** [comment] 2023-04-01 17:59
I _had_ a different issue. The issue was having amdvlk installed. Once I uninstalled it, SteamVR was working again. Then a day or two later _this_ issue cropped up.

**Comment by im-0** [comment] 2023-04-03 02:07
Same here.

* Distribution: Fedora 38, KDE Plasma Wayland, Steam from flatpak
* SteamVR version: 1.26.1
* Steam client version: Mar 24 2023, at 17:20:43
* Opted into Steam client beta?: No
* Graphics driver version: Mesa 22.3.5 (inside flatpak)

**Comment by c-x-berger** [comment] 2023-04-05 00:26
Can confirm as well. Identical behavior to the opening post.

* Distribution: Endeavor OS
* SteamVR version: 1.26.1 beta
* Steam client version: Mar 24 2023, at 17:20:43
* Opted into Steam client beta?: No
* Graphics driver version: Mesa 23.0.1

**Comment by ZarathustraDK** [comment] 2023-04-05 09:56
Getting the same error. SteamVR seems to work fine game-wise though. Also getting the Bluetooth error (BT-232).

- Distribution/kernel: Arch 6.2.9.arch1-1 with KDE DE
- SteamVR version: 1.26.1 beta
- Steam client version: Mar 24 2023, at 17:20:43
- Opted into Steam client beta?: Yes
- Graphics driver version: Mesa 23.0.1-2
- Ryzen 7900X3D & Radeon 7900 XTX

**Comment by KevinFleischer** [comment] 2023-05-11 19:48
I have trouble with steamvr all the way. When I try to start HL Alyx the game crashes with the 303 error.
I have a Tuxedo Stellaris with this configuration:
OS: Kubuntu 22.04
KDE-Plasma-Version: 5.24.7
KDE-Frameworks-Version: 5.92.0
Qt-Version: 5.15.3
Kernel-Version: 6.2.0-10005-tuxedo (64-bit)
Grafik-Plattform: X11
Prozessoren: 20 × 12th Gen Intel® Core™ i9-12900H
Memory: 31,1 GiB RAM
Grafikprozessor: NVIDIA GeForce RTX 3070 Ti Laptop GPU/PCIe/SSE2

**Comment by RinLovesYou** [comment] 2023-05-19 21:56
happens in normal for me, and beta

**Comment by jarrard** [comment] 2023-05-20 00:18
try installing steam-native-runtime if your on arch as it pulls in a lot of dependencies that people miss when just installing the steam package.

**Comment by RinLovesYou** [comment] 2023-05-20 03:22
Still happens under steam-native

To clarify: this is solved by not using the new steam client beta and not using stramvr beta.

**Comment by caseif** [comment] 2023-06-23 00:05
Just noting that both issues are still occurring (at least on my machine) as of 1.26.3.

**Comment by AAGaming00** [comment] 2023-06-24 18:14
Now that the beta UI has reached stable, there doesn't seem to be any workaround for this.

**Comment by Rewarp** [comment] 2023-06-25 14:35
Just got hit with this bug after getting my Valve Index. Running on openSUSE Tumbleweed snapshot 20230620, on Plasma Wayland. I am running Beta for both the Steam Client from the openSUSE repos and SteamVR, since I might as well test things out if it is broken for VR at present. I encountered several issues along the way and since this is a fresh Valve Index, maybe this will help someone down the line.

First, I had to export `/usr/sbin` to PATH as getcap is only visible to sudo or root.

`export PATH=/usr/sbin:$PATH`

Then my workaround for skipping the tour which was blocking my setup follows this [bug](https://github.com/ValveSoftware/SteamVR-for-Linux/issues/579#issue-1685177017), where in `.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/` I renamed `steamtours.sh` to `steamtours.sh.old` or basically any other name.

Finally, I reached the 303 error, and worked around it by adding `-hmd=SteamVR` to the app I want to launch. In this case Beat Saber, and launching it from the desktop.

**Comment by caseif** [comment] 2023-08-18 15:30
Both issues are no longer occurring on my system as of 1.27.2.

**Comment by Rewarp** [comment] 2023-08-21 03:24
I can confirm my Index and SteamVR just works :tm: in the latest updates without any of the additional steps I stated in https://github.com/ValveSoftware/SteamVR-for-Linux/issues/572#issuecomment-1606115607

**Comment by kisak-valve** [comment] 2023-09-23 01:42
Closing per the last couple comments.

**Closed by kisak-valve** 2023-09-23 01:42 UTC
Labels: bug, Need Retest
