### ISSUE TITLE
[BUG] SteamVR does not start: Failed to connect to window manager (497)

### ISSUE THREAD

**Issue by jessicamaybe** [ValveSoftware/SteamVR-for-Linux#672] opened 2024-02-01 07:15 UTC
**Describe the bug**
SteamVR does not start

**To Reproduce**
1. Plug in Valve Index
2. Start SteamVR

**Expected behavior**
SteamVR starts and begins room setup

**System Information (please complete the following information):**
- Distribution: Bazzite
- SteamVR version: 1.27.5 beta and 2.2.3
- Opted into Steam client beta?: Tried with and without Steam beta
- Graphics driver version:  Mesa 23.3.4
- Gist for SteamVR System Information: [See [instructions](https://github.com/ValveSoftware/SteamVR-for-Linux/blob/master/CapturingSystemReport.md)]

**Additional context**
Most notably from the logs in ".steam/steam/logs/vrclient_steam.txt" is:
`[Status Alert] Failed to connect to window manager (497)`

Logs from latest SteamVR `.steam/steam/logs/vrclient_vrstartup.txt`:
```
Wed Jan 31 2024 22:47:48.541206 [Info] - //==============================================================================================
Wed Jan 31 2024 22:47:48.541239 [Info] - ================================================================================================
Wed Jan 31 2024 22:47:48.541260 [Info] - ================================================================================================
Wed Jan 31 2024 22:47:48.541297 [Info] - vrstartup 2.2.3 startup with PID=8115, config=/var/home/bazzite/.local/share/Steam/config, runtime=/var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR
Wed Jan 31 2024 22:47:48.541340 [Info] - vrclient type=VRApplication_Bootstrapper
Wed Jan 31 2024 22:47:48.541360 [Info] - Skipping HMD presence checks.
Wed Jan 31 2024 22:47:48.541415 [Info] - Set thread 0x7f65c10b86c0 priority to: -15
Wed Jan 31 2024 22:47:48.542208 [Info] - [Settings] Load Default Json Settings from /var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR/drivers/htc/resources/settings/default.vrsettings
Wed Jan 31 2024 22:47:48.542281 [Info] - [Settings] Load Default Json Settings from /var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR/drivers/lighthouse/resources/settings/default.vrsettings
Wed Jan 31 2024 22:47:48.542332 [Info] - [Settings] Load Default Json Settings from /var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR/drivers/null/resources/settings/default.vrsettings
Wed Jan 31 2024 22:47:48.542397 [Info] - [Settings] Load Default Json Settings from /var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR/drivers/vrlink/resources/settings/default.vrsettings
Wed Jan 31 2024 22:47:48.542584 [Info] - [Settings] Load Default Json Settings from /var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR/resources/settings/default.vrsettings
Wed Jan 31 2024 22:47:48.542941 [Info] - [Settings] Load Json Settings from /var/home/bazzite/.local/share/Steam/config/steamvr.vrsettings
Wed Jan 31 2024 22:47:48.543134 [Info] - CIPCPipe::ConnectPipe(SteamVR_Namespace) attempting connect to /steamvr/SteamVR_Namespace
Wed Jan 31 2024 22:47:48.543161 [Info] - Unable to connect to pipe errno=111
Wed Jan 31 2024 22:47:48.543245 [Info] - Starting vrserver process: /var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrserver -waitformonitor -ipccontrolfilepath /tmp/SteamVR-IPCControlFile-8115  in /var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR/
Wed Jan 31 2024 22:47:48.694415 [Info] - vrserver pid 8235
Wed Jan 31 2024 22:47:48.694491 [Info] - CIPCPipe::ConnectPipe(SteamVR_Namespace) attempting connect to /steamvr/SteamVR_Namespace
Wed Jan 31 2024 22:47:48.694547 [Info] - CSharedResourceNamespaceClient::Init(): received namespace data 8235
Wed Jan 31 2024 22:47:48.694590 [Info] - CIPCPipe::ConnectPipe(VR_ServerPipe_8235) attempting connect to /steamvr/VR_ServerPipe_8235
Wed Jan 31 2024 22:47:50.036492 [Info] - Received success response from vrserver connect
Wed Jan 31 2024 22:47:52.140964 [Info] - Timed out waiting for a good app key
Wed Jan 31 2024 22:47:52.141021 [Info] - App key after connect message:steam.overlay.250820
Wed Jan 31 2024 22:47:52.146452 [Info] - CIPCPipe::ConnectPipe(VR_CompositorPipe_8235) attempting connect to /steamvr/VR_CompositorPipe_8235
Wed Jan 31 2024 22:47:52.146480 [Info] - Unable to connect to pipe errno=111
Wed Jan 31 2024 22:47:52.165230 [Info] - WARNING: NOT running in a Steam for Linux pressure-vessel container runtime. Your SteamVR installation is misconfigured.
Wed Jan 31 2024 22:47:52.165331 [Info] - Starting vrcompositor process: /var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor-launcher.sh args: , in folder /var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR/bin/linux64
Wed Jan 31 2024 22:47:52.183001 [Info] - CIPCPipe::ConnectPipe(VR_CompositorPipe_8235) attempting connect to /steamvr/VR_CompositorPipe_8235
Wed Jan 31 2024 22:47:52.183050 [Info] - Unable to connect to pipe errno=111
Wed Jan 31 2024 22:47:52.283174 [Info] - CIPCPipe::ConnectPipe(VR_CompositorPipe_8235) attempting connect to /steamvr/VR_CompositorPipe_8235
Wed Jan 31 2024 22:47:52.339180 [Info] - Error reading from socket
Wed Jan 31 2024 22:47:52.339223 [Info] - Unable to read message from socket: 104
Wed Jan 31 2024 22:47:52.339257 [Info] - GetNextMessage failed while waiting for message of type 501 on pipe VR_CompositorPipe_8235
Wed Jan 31 2024 22:47:52.339299 [Info] - Invalid response to connect message. Connect failed
Wed Jan 31 2024 22:47:52.360155 [Info] - Started /var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrmonitor with pid 8292

```

Logs from SteamVR 1.27.5 Linux Branch `.steam/steam/logs/vrclient_vrstartup.txt`
```
Wed Jan 31 2024 22:40:23.450678 [Info] - //==============================================================================================
Wed Jan 31 2024 22:40:23.450936 [Info] - ================================================================================================
Wed Jan 31 2024 22:40:23.450956 [Info] - ================================================================================================
Wed Jan 31 2024 22:40:23.450978 [Info] - vrstartup 1.27.5 startup with PID=6829, config=/var/home/bazzite/.local/share/Steam/config, runtime=/var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR
Wed Jan 31 2024 22:40:23.451023 [Info] - vrclient type=VRApplication_Bootstrapper
Wed Jan 31 2024 22:40:23.451771 [Info] - [Settings] Load Default Json Settings from /var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR/drivers/htc/resources/settings/default.vrsettings
Wed Jan 31 2024 22:40:23.451830 [Info] - [Settings] Load Default Json Settings from /var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR/drivers/lighthouse/resources/settings/default.vrsettings
Wed Jan 31 2024 22:40:23.451877 [Info] - [Settings] Load Default Json Settings from /var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR/drivers/null/resources/settings/default.vrsettings
Wed Jan 31 2024 22:40:23.452052 [Info] - [Settings] Load Default Json Settings from /var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR/resources/settings/default.vrsettings
Wed Jan 31 2024 22:40:23.452407 [Info] - [Settings] Load Json Settings from /var/home/bazzite/.local/share/Steam/config/steamvr.vrsettings
Wed Jan 31 2024 22:40:23.529939 [Info] - CIPCPipe::ConnectPipe(SteamVR_Namespace) attempting connect to /steamvr/SteamVR_Namespace
Wed Jan 31 2024 22:40:23.530031 [Info] - Unable to connect to pipe errno=111
Wed Jan 31 2024 22:40:23.530132 [Info] - Starting vrserver process: /var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrserver
Wed Jan 31 2024 22:40:23.681460 [Info] - CIPCPipe::ConnectPipe(SteamVR_Namespace) attempting connect to /steamvr/SteamVR_Namespace
Wed Jan 31 2024 22:40:23.681568 [Info] - CSharedResourceNamespaceClient::Init(): received namespace data 6935
Wed Jan 31 2024 22:40:23.681638 [Info] - CIPCPipe::ConnectPipe(VR_ServerPipe_6935) attempting connect to /steamvr/VR_ServerPipe_6935
Wed Jan 31 2024 22:40:24.909837 [Info] - Received success response from vrserver connect
Wed Jan 31 2024 22:40:27.016259 [Info] - Timed out waiting for a good app key
Wed Jan 31 2024 22:40:27.016326 [Info] - App key after connect message:steam.overlay.250820
Wed Jan 31 2024 22:40:27.021970 [Info] - CIPCPipe::ConnectPipe(VR_CompositorPipe_6935) attempting connect to /steamvr/VR_CompositorPipe_6935
Wed Jan 31 2024 22:40:27.022002 [Info] - Unable to connect to pipe errno=111
Wed Jan 31 2024 22:40:27.044328 [Info] - Starting vrcompositor process: /var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor-launcher 
Wed Jan 31 2024 22:40:27.065274 [Info] - CIPCPipe::ConnectPipe(VR_CompositorPipe_6935) attempting connect to /steamvr/VR_CompositorPipe_6935
Wed Jan 31 2024 22:40:27.065323 [Info] - Unable to connect to pipe errno=111
Wed Jan 31 2024 22:40:27.165448 [Info] - CIPCPipe::ConnectPipe(VR_CompositorPipe_6935) attempting connect to /steamvr/VR_CompositorPipe_6935
Wed Jan 31 2024 22:40:27.227101 [Info] - Error reading from socket
Wed Jan 31 2024 22:40:27.227153 [Info] - Unable to read message from socket: 104
Wed Jan 31 2024 22:40:27.227187 [Info] - GetNextMessage failed while waiting for message of type 501 on pipe VR_CompositorPipe_6935
Wed Jan 31 2024 22:40:27.227222 [Info] - Invalid response to connect message. Connect failed
Wed Jan 31 2024 22:40:27.249699 [Info] - Started /var/home/bazzite/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrmonitor with pid 6974
```

**Comment by SentineI** [comment] 2024-02-19 19:49
I am also have the same (or very similar) problem, since about a week ago (but it could have started up to 2 weeks ago).  I have tried every fix I can think of without luck (e.g. uninstall & reinstall SteamVR, switch to beta version of SteamVR, boot older kernels, install older NVidia drivers).  

It seems to be a software issue, as I don't get the problem on a clean test install of Ubuntu 22.04 (but I am not going to wipe my whole PC just to get VR working).

**Describe the bug**
SteamVR doesn't properly start, giving the error message "Failed to connect to window manager" (see below for complete messages).

**To Reproduce**
1. I plug in (power to) my VR headset (a HTC Vive).
2. I start the Steam, then go to View > Start SteamVR.  At this point it opens a window saying "SteamVR Error" "SteamVR failed to initialize for unknown reasons. (Error: Not initialized (109) (109))".
3. Then the SteamVR window opens, and above it is another window saying "Failed to connect to window manager" "SteamVR failed to connect to the window manager.  You may need to restart your session or SteamVR" (but doing that does not help).

The VR headset status icon is green, but the actual VR headset's display is black.  I didn't try starting any games, since I don't imagine they'll work any better than SteamVR Home (which I don't think it even tried starting).

**Expected behavior**
No error message, and SteamVR Home would be running.

**System Information (please complete the following information):**
- Distribution: Ubuntu 22.04.04 LTS
- SteamVR version: 2.3.5
- Steam client version: 1705108172 (Build Date:  Sat, Jan 13 12:52)
- Opted into Steam client beta?: No
- Graphics driver version:  NVidia 535.154.05, Mesa 23.2.1-1ubuntu3.1~22.04.2 (LLVM 15.0.7)
- Gist for SteamVR System Information: https://gist.github.com/SentineI/74a09f6d5199f04495644c3362b64053
(note that I have replaced /home/USER with ~)

I am using kernel 6.5.0-18-generic, but booting older kernels did not help.

**Screenshots**
I don't think screenshots are needed.

**Additional context**
Here is what I found from "~/.steam/steam/logs/vrclient_vrstartup.txt":
```
Mon Feb 19 2024 19:12:52.143402 [Info] - //==============================================================================================
Mon Feb 19 2024 19:12:52.149336 [Info] - ================================================================================================
Mon Feb 19 2024 19:12:52.149401 [Info] - ================================================================================================
Mon Feb 19 2024 19:12:52.149468 [Info] - vrstartup 2.3.5 startup with PID=6750, config=~/.steam/debian-installation/config, runtime=~/.steam/debian-installation/steamapps/common/SteamVR
Mon Feb 19 2024 19:12:52.149603 [Info] - vrclient type=VRApplication_Bootstrapper
Mon Feb 19 2024 19:12:52.149666 [Info] - Skipping HMD presence checks.
Mon Feb 19 2024 19:12:52.157974 [Info] - Set thread 0x7ffb276bf640 priority to: -15
Mon Feb 19 2024 19:12:52.159959 [Info] - [Settings] Load Default Json Settings from ~/.steam/debian-installation/steamapps/common/SteamVR/drivers/htc/resources/settings/default.vrsettings
Mon Feb 19 2024 19:12:52.160115 [Info] - [Settings] Load Default Json Settings from ~/.steam/debian-installation/steamapps/common/SteamVR/drivers/lighthouse/resources/settings/default.vrsettings
Mon Feb 19 2024 19:12:52.160257 [Info] - [Settings] Load Default Json Settings from ~/.steam/debian-installation/steamapps/common/SteamVR/drivers/null/resources/settings/default.vrsettings
Mon Feb 19 2024 19:12:52.160441 [Info] - [Settings] Load Default Json Settings from ~/.steam/debian-installation/steamapps/common/SteamVR/drivers/vrlink/resources/settings/default.vrsettings
Mon Feb 19 2024 19:12:52.160974 [Info] - [Settings] Load Default Json Settings from ~/.steam/debian-installation/steamapps/common/SteamVR/resources/settings/default.vrsettings
Mon Feb 19 2024 19:12:52.162101 [Info] - [Settings] Load Json Settings from ~/.steam/debian-installation/config/steamvr.vrsettings
Mon Feb 19 2024 19:12:52.162645 [Info] - CIPCPipe::ConnectPipe(SteamVR_Namespace) attempting connect to /steamvr/SteamVR_Namespace
Mon Feb 19 2024 19:12:52.162720 [Info] - Unable to connect to pipe errno=111
Mon Feb 19 2024 19:12:52.162948 [Info] - Starting vrserver process: ~/.steam/debian-installation/steamapps/common/SteamVR/bin/linux64/vrserver -waitformonitor -ipccontrolfilepath /tmp/SteamVR-IPCControlFile-6750  in ~/.steam/debian-installation/steamapps/common/SteamVR/
Mon Feb 19 2024 19:12:52.519088 [Info] - vrserver pid 6878
Mon Feb 19 2024 19:12:52.519261 [Info] - CIPCPipe::ConnectPipe(SteamVR_Namespace) attempting connect to /steamvr/SteamVR_Namespace
Mon Feb 19 2024 19:12:52.519405 [Info] - CSharedResourceNamespaceClient::Init(): received namespace data 6878
Mon Feb 19 2024 19:12:52.519524 [Info] - CIPCPipe::ConnectPipe(VR_ServerPipe_6878) attempting connect to /steamvr/VR_ServerPipe_6878
Mon Feb 19 2024 19:12:54.650776 [Info] - Received success response from vrserver connect
Mon Feb 19 2024 19:12:56.779617 [Info] - Timed out waiting for a good app key
Mon Feb 19 2024 19:12:56.779751 [Info] - App key after connect message:steam.overlay.250820
Mon Feb 19 2024 19:12:56.798500 [Info] - CIPCPipe::ConnectPipe(VR_CompositorPipe_6878) attempting connect to /steamvr/VR_CompositorPipe_6878
Mon Feb 19 2024 19:12:56.798607 [Info] - Unable to connect to pipe errno=111
Mon Feb 19 2024 19:12:56.834711 [Info] - WARNING: NOT running in a Steam for Linux pressure-vessel container runtime. Your SteamVR installation is misconfigured.
Mon Feb 19 2024 19:12:56.834940 [Info] - Starting vrcompositor process: ~/.steam/debian-installation/steamapps/common/SteamVR/bin/linux64/vrcompositor-launcher.sh args: , in folder ~/.steam/debian-installation/steamapps/common/SteamVR/bin/linux64
Mon Feb 19 2024 19:12:57.009992 [Info] - CIPCPipe::ConnectPipe(VR_CompositorPipe_6878) attempting connect to /steamvr/VR_CompositorPipe_6878
Mon Feb 19 2024 19:12:57.010109 [Info] - Unable to connect to pipe errno=111
Mon Feb 19 2024 19:12:57.110323 [Info] - CIPCPipe::ConnectPipe(VR_CompositorPipe_6878) attempting connect to /steamvr/VR_CompositorPipe_6878
Mon Feb 19 2024 19:12:57.110413 [Info] - Unable to connect to pipe errno=111
Mon Feb 19 2024 19:12:57.210622 [Info] - CIPCPipe::ConnectPipe(VR_CompositorPipe_6878) attempting connect to /steamvr/VR_CompositorPipe_6878
Mon Feb 19 2024 19:12:57.787247 [Info] - Error reading from socket
Mon Feb 19 2024 19:12:57.787359 [Info] - Unable to read message from socket: 104
Mon Feb 19 2024 19:12:57.787465 [Info] - GetNextMessage failed while waiting for message of type 501 on pipe VR_CompositorPipe_6878
Mon Feb 19 2024 19:12:57.787538 [Info] - Invalid response to connect message. Connect failed
Mon Feb 19 2024 19:12:57.806094 [Info] - Started ~/.steam/debian-installation/steamapps/common/SteamVR/bin/linux64/vrmonitor with pid 6949
```
(note that I have replaced /home/USER with ~)

The relevant errors are clearly "`attempting connect to /steamvr/SteamVR_Namespace`" & "`attempting connect to /steamvr/VR_CompositorPipe_6878`" followed by "`Unable to connect to pipe errno=111`".

The following warning may be related, but I am not familiar enough with Steam to know how to fix it: 
`WARNING: NOT running in a Steam for Linux pressure-vessel container runtime. Your SteamVR installation is misconfigured.`

**Comment by SentineI** [comment] 2024-02-19 20:14
I am now suspecting this recent SteamVR update is the cause: 
https://steamdb.info/patchnotes/13330821/
However it looks far too complicated to manually install an older version (it appears to require good understanding of Steam's inner workings), and I have no desire to break my Steam installation completely: 
https://github.com/ValveSoftware/SteamVR-for-Linux/issues/639#issuecomment-1817538299

**Comment by SentineI** [comment] 2024-02-19 20:23
I have now tried renaming the "steamvr.vrsettings" file & the "vrappconfig" folder in "~/.steam/debian-installation/config/", before starting SteamVR (in the hope a config file was corrupt), but that didn't help either.

**Comment by Linubuser** [comment] 2024-02-19 20:29
This fix error 497 for me on Bazzite OS.

1. Add the following Launch Options to SteamVR:
steam-runtime-launch-options -- %command%

2. Launch SteamVR.
A menu will pop up and set the following options:
Container runtime to: None
SDL video driver to: x11

3. Click: run

**Comment by SentineI** [comment] 2024-02-19 20:40
I have now tried with SteamVR beta 2.4.1, but this doesn't fix the issue either.  I'll leave it on the beta version in the hope this gets a fix first.

@Linubuser 
> This fix error 497 for me on Bazzite OS.

Thanks for the suggestion, but it didn't help me.  I tried it with both normal & beta versions of SteamVR.

**Comment by SentineI** [comment] 2024-02-20 19:40
An update: I connect my "clean test install of Ubuntu 22.04" HD to my main system, and "mount --bind"ed it's copy of Steam where my version was.  I was then able to start it's Steam fine, but as soon as I started it's SteamVR, I got the same error message window as before.  This seems to suggest that SteamVR is not intrinsically broken, but rather it doesn't like something about by Ubuntu installation - although I have no idea what.

**Comment by SentineI** [comment] 2024-02-24 15:13
It took a lot of effort, but I've been able to find out what caused my SteamVR problem, why it caused a problem, and how to fix it:

The problem was caused when I started the Flatpak version of Steam, after I'd effectively done the following: 
`sudo mount --bind ~/.steam ~/.var/app/com.valvesoftware.Steam/.steam`
i.e. I had mounted my native Steam folder so that the Flatpak version would use it.  While this used to work in the past, seemingly without problem, I suspect that some recent(ish) change to Steam stopped it from fixing what happened next.

After the Flatpak version of Steam was started, it deleted a lot of files & symlinks in these two folders:
`~/.steam/debian-installation/ubuntu12_64/`
`~/.steam/debian-installation/ubuntu12_32/`
(Note that your Steam installation may not use a "debian-installation" folder, as I believe this is due to how I originally installed Steam - just search for "ubuntu12_64" in the ".steam" folder in that case.)

I hadn't notice this cause a problem for any of the games I normally play, but going by the SteamVR error messages, it prevented Steam from running games in the "Linux pressure-vessel container runtime".  In SteamVR's case this then caused it to "Failed to initialize mirror window" on the on my VR headset, and thus "Failed to connect to window manager" etc.

It looks like Flatpak's Steam wrapper automatically fixes certain Steam folders, and has done so for at least several years: 
https://github.com/flathub/com.valvesoftware.Steam/blob/beta/steam_wrapper/steam_wrapper.py
This has obviously been breaking my native Steam folder, but until recently(ish) it seems that native Steam had been detecting this corruption & automatically fixing it, as it USED to show some kind of installation window the first time I started it after I'd used the Flatpak version...  HOWEVER more recently it has stopped doing that (for whatever reason).  

**While it would be nice if Steam did automatically fix itself, it's not really a Steam bug.  @Linubuser if your problem has a similar cause, then I think you should close this bug report, so that Valve doesn't waste time looking at it.**

How did I fix it?  After deleting those two folders, I took the easy way out and rsync-ed an exact copy of those folders from a backup I'd taken before the problem had happened (making sure to preserve symlinks):
`rsync -v --xattrs --specials --devices --links --hard-links --perms --times --open-noatime --group --owner --recursive --one-file-system BACKUPFOLDER/debian-installation/{ubuntu12_64,ubuntu12_32} ~/.steam/debian-installation/ --dry-run`
Another way would be to temporarily install your distro on a spare HD, set it up with exactly the same username as your real Linux installation (so the symlinks are correct), install Steam, and then copy those folders to your Steam folder (after deleting the corrupted folders), making sure to preserve symlinks.

Another (and much simpler) way that OUGHT to fix it is to just delete the "ubuntu12_32" & "ubuntu12_64" folders (beware Steam will no-longer start!), and then reinstall the original Steam package (either directly from Steam's website OR using your distro's package manager - however you originally installed it).  However I have NOT tested this method, so I can't confirm if it works, nor if there might be any unwanted side-effects.

WARNING: Make sure you have taken a full system backup/snapshot of your system, before running the above "rsync" command.  Although it shouldn't cause any serious problems, since the --delete option is not being used (and is not necessary since I'd already said to delete the corrupted folders).

**Comment by MalikuMane** [comment] 2024-02-25 22:53
I'd argue that just getting the pop ups to stop on startup solves the issue given in the title.

**Comment by HReflex** [comment] 2024-04-30 03:35
> This fix error 497 for me on Bazzite OS.
> 
> 1. Add the following Launch Options to SteamVR:
>    steam-runtime-launch-options -- %command%
> 2. Launch SteamVR.
>    A menu will pop up and set the following options:
>    Container runtime to: None
>    SDL video driver to: x11
> 3. Click: run

Thank you! Im on Fedora 40 w/ KDE and that fixed it for me.

**Comment by TTimo** [comment] 2024-05-02 22:59
Closing. Please open a new report with the requested information if you experience this in latest SteamVR beta. Please do not use `steam-runtime-launch-options` or disable the Steam for Linux runtime configuration. You should be starting SteamVR from the Steam client.

**Closed by TTimo** 2024-05-02 22:59 UTC
Labels: bug
