### ISSUE TITLE
[BUG] SteamVR won't start at all (affects both beta and stable)

### ISSUE THREAD

**Issue by lightstream** [ValveSoftware/SteamVR-for-Linux#643] opened 2023-11-18 06:37 UTC
**Describe the bug**
SteamVR will not start up at all.

**To Reproduce**
1. Start SteamVR by clicking the goggles icon or by starting it from your library
2. The headset does not display anything
3. SteamVR displays an error: Oh no! SteamVR has encountered an unexpected problem. (500)

**Expected behavior**
SteamVR to start up as normal.

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: 2.1.4
- Steam client version: 1700272093
- Opted into Steam client beta?: Yes
- Graphics driver version:  Mesa 23.2.1-arch1.2
- Gist for SteamVR System Information: https://gist.github.com/lightstream/327c7c8274ffb85de91ca6c28d887279

**Screenshots**
![image](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/830505/4ea68e3b-e02c-4f71-a4c2-ded142ada21d)

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by CarbonNotes** [comment] 2023-11-18 07:29
Same issue on Debian Testing + KDE X11, SteamVR 2.1.4, Mesa 23.2.1-1, Kernel 6.6.1

**Comment by Danielduel** [comment] 2023-11-18 07:50
This looks like the duplicate of https://github.com/ValveSoftware/SteamVR-for-Linux/issues/639

**Comment by lightstream** [comment] 2023-11-18 11:42
Confirmed duplicate of #639 - I also have those messages in vrcompositor.txt:
```
 [Error] - Failed to get blur texture lod 0
 [Error] - Failed to init graphics device
 [Info] - Failed to kill gpu-trace
 [Info] - Failed to initialize compositor
 [Info] - Failed to start compositor: VRInitError_Compositor_CreateBlurTexture
```

**Closed** 2023-11-18 11:42 UTC
Labels: bug

**Comment by SquadFM** [comment] 2023-11-18 16:08
Same issue with 2.1.4

[BUG] Linux SteamVR 2.1.4 crashes right after launch

**Describe the bug**
Upon starting Steam and then SteamVR (2.1.4) the folloing error message appears in the SteamVR window: "SteamVR Fail - Oh no! SteamVR has encountered and unexpected problem. Restart SteamVR (500)". Restarting SteamVR does not fix the issue, neither does restarting Steam or the PC. 

**To Reproduce**
1. Start Steam
2. Turn your Valve Index on
3. Start SteamVR
4. You will see the error message

**Expected behavior**
I expect SteamVR to start without showing an error message and to play games in VR

**System Information (please complete the following information):**
- Distribution: Arch (EndevourOS)
- SteamVR version: 2.1.4
- Steam client version: 1700160213, build date: Thu, Nov 16 13:23 UTC -05:00 
- Opted into Steam client beta?: No
- Graphics driver version:  [run `nvidia-settings` or `vulkaninfo | grep driverInfo`: 545.29.02 (nVidia)
- Gist for SteamVR System Information: https://gist.github.com/SquadFM/676718fc1394f3ff824afb8d1c7777eb

**Additional context**
Before the update to 2.1.4 SteamVR was working and I could play VR games.

**Comment by Danielduel** [comment] 2023-11-18 16:29
Hi @SquadFM 
This issue was moved to https://github.com/ValveSoftware/SteamVR-for-Linux/issues/639
