### ISSUE TITLE
[BUG] Controller see-through in open area

### ISSUE THREAD

**Issue by whinis** [ValveSoftware/SteamVR-for-Linux#451] opened 2021-07-05 19:41 UTC
**Describe the bug**
The shader on the controllers appear to be partially transparent in the SteamVR land. However work fine everywhere else

**To Reproduce**
Unsure, see it every time I launch

**Expected behavior**
Controllers should be solid and not see-through

**System Information (please complete the following information):**
- Distribution:Linux Mint 20.1
- SteamVR version:1.17.16
- Steam client version:  1623193086
- Opted into Steam client beta?: No
- Graphics driver version: 
``` vulkaninfo | grep driverInfo
	driverInfo         = Mesa 20.2.6 (ACO)
	driverInfo                                           = Mesa 20.2.6 (ACO)
```
- Gist for SteamVR System Information: https://gist.github.com/whinis/8a2bb72b0fc787f1e5380b78826596f3

**Screenshots**
![image](https://user-images.githubusercontent.com/7612064/124512808-4c0b0680-dda7-11eb-829f-093818b7c13d.png)

**Comment by ChristophHaag** [comment] 2021-07-05 19:49
unfortunately an older bug, see also #430

**Comment by kisak-valve** [comment] 2021-07-05 20:11
Closing as a duplicate of #430.

**Closed by kisak-valve** 2021-07-05 20:11 UTC
Labels: bug
