### ISSUE TITLE
"Pair controller" crashes

### ISSUE THREAD

**Issue by tcriess** [ValveSoftware/SteamVR-for-Linux#47] opened 2017-04-27 09:17 UTC
#### Your system information
* Steam client version (build number or date): 1493162727
* Distribution (e.g. Ubuntu): Ubuntu 17.04
* Graphics driver version (run nvidia-settings): 381.09
* Gist for SteamVR System Information: https://gist.github.com/tcriess/89c8934b769968807062a4671e32618c
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When trying to pair the tracker by using the "pair controller" menu entry, nothing happens (the problem with the trackers is that they are easily un-paired unintentionally, thus essentially bricking them). In syslog the last entry usually is something like "vrmonitor[8893]: segfault at 7f7551c9513e ip 00007f75111d0640 sp 00007ffc44009cd8 error 4 in libQt5Core.so.5[7f751100e000+533000]", so I assume a crash somewhere.
Possible regression of issue #33 

#### Steps for reproducing this issue:
1. start SteamVR
2. select "Devices > Pair Controller"

**Comment by kisak-valve** [comment] 2017-04-27 12:48
Hello @tcriess, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. In particular, if you find any relevant CrashIDs or minidumps related to this issue, please include them in this issue report. You can put relevant minidump(s) from `/tmp/dumps/` into an archive and drag and drop the archive into the comment box.

**Comment by tcriess** [comment] 2017-04-27 12:58
Hi, sure:
System information gist: https://gist.github.com/tcriess/a5c8c256a5df8a7615e1121eedbc6d60
Dumps: [dump.zip](https://github.com/ValveSoftware/SteamVR-for-Linux/files/961621/dump.zip)

**Comment by kisak-valve** [comment] 2017-04-27 13:09
For reference, crash*.dmp are the relevant SIGSEGV in libQt5Core. The issue is pretty deep in Qt5, so it may not be an issue with SteamVR.

**Comment by tcriess** [comment] 2017-04-27 15:16
Second that. I also tried using different Qt5 versions, 5.7.1 and current 5.8.x, none of which made a difference.

**Comment by johnv-valve** [comment] 2017-04-27 18:20
Just to clarify - you only see this when pairing the HTC Vive Tracker? Not the regular controllers?

**Comment by tcriess** [comment] 2017-04-27 18:32
AFAIK there is only the "Pair controller" menu entry, and no separate menu entry for the tracker (although the manual says there is one...). And it happens instantly whenever this menu entry is selected, no window pops up, which means no chance to pair anything, so this also applies to controller pairing (my controllers are already paired though, and I haven't (yet) managed to un-pair them, so in this case the intention was indeed to (re-)pair the trackers).

**Comment by EndeavourAccuracy** [comment] 2017-05-04 19:18
I'm running into the same issue.
One of my controllers has a blue light, and trying to pair them crashes.
This means I can only use 1 controller in, for example, Serious Sam VR.

**Comment by claytmcneil** [comment] 2017-05-19 01:18
I've also run into the same issue. Only workaround was to boot into a Windows first, pair, and then boot back into Ubuntu.

**Comment by johnv-valve** [comment] 2017-05-26 19:15
Should be fixed in the current beta
http://steamcommunity.com/games/250820/announcements/detail/1256914311380287819

**Closed by johnv-valve** 2017-05-26 19:15 UTC

**Comment by EndeavourAccuracy** [comment] 2017-05-27 08:05
Fixed the issue here.
Thanks!

Tiny suggestion for the "Pair a new Controller" screen, to visually help the user even further:
http://i.imgur.com/dDGjg7t.png
Mirror: https://image.ibb.co/mQf1kv/difference.png
Left the current image, right my suggestion (draft).
