### ISSUE TITLE
Unable to Get Past Vive Room Setup on Ubuntu 17.10

### ISSUE THREAD

**Issue by georgewsinger** [ValveSoftware/SteamVR-for-Linux#84] opened 2017-12-07 13:35 UTC
#### Your system information
* Steam client version (build number or date): Oct 30 2017, at 19:09:46
* Distribution (e.g. Ubuntu): Ubuntu 17.10
* Graphics driver version (run nvidia-settings): 387.34
* Gist for SteamVR System Information: https://gist.github.com/georgewsinger/429d151ef68cb4f303377595f31e00b2
* Opted into Steam client beta?: No
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I'm unable to complete the Vive Room Setup on Ubuntu 17.10 using `nvidia-387` drivers. Specifically, it says "Headset Not Visible" even though (i) the headset does seem to be recognized in the SteamVR Status menu and (ii) the headset is visible when I launch the SteamVR Room Setup in Windows using the same machine. Here's what it looks like in Ubuntu:

![pic](https://i.imgur.com/bmDlJ1u.png)

And here is the tail end of my `vrserver.txt` log:

```
Thu Dec 07 2017 11:47:59.125159 - lighthouse: VRC-D4B105EBBE C: ----- BOOTSTRAPPED base 775ADEB0 (immediate) distance 3.13m velocity 0.09m/s recorded pitch ~24.0 deg roll ~-15.9 deg -----
Thu Dec 07 2017 11:48:00.316710 - lighthouse: LHR-FF421D45 C: Trying to add a secondary base E2F61B3C: Samples didn't yield successful bootstrap pose
Thu Dec 07 2017 11:48:01.176479 - lighthouse: VRC-D4B105EBBE C: Calibration failed: no optical samples from base 775ADEB0 for 2001ms
Thu Dec 07 2017 11:48:06.184635 - lighthouse: VRC-D4B105EBBE C: Trying to start tracking from base 775ADEB0: Not enough contiguous samples for a bootstrap pose
Thu Dec 07 2017 11:48:06.184669 - lighthouse: VRC-D4B105EBBE C: Trying to start tracking from base E2F61B3C: Samples didn't yield successful bootstrap pose
Thu Dec 07 2017 11:48:07.370937 - lighthouse: VRC-D4B105EBBE C: Trying to start tracking from base E2F61B3C: Could boot, but disallowed by LighthouseDB
Thu Dec 07 2017 11:48:08.924515 - 1 - in use time less than now: 0x486e707ae3fe  < 0x486e707ae04c
Thu Dec 07 2017 11:48:14.909500 - lighthouse: LHR-FF421D45 C: Resetting tracking: no optical samples from base 775ADEB0 for 2000ms
Thu Dec 07 2017 11:48:14.909542 - lighthouse: Stopped tracking with universe 1512584546
Thu Dec 07 2017 11:48:16.125024 - lighthouse: LHR-FF421D45 C: ----- BOOTSTRAPPED base 775ADEB0 (immediate) distance 3.16m velocity 0.01m/s recorded pitch ~24.0 deg roll ~-15.9 deg -----
Thu Dec 07 2017 11:48:21.226713 - lighthouse: LHR-FF421D45 C: ----- CALIBRATED base 775ADEB0 at pitch 23.59 deg roll -15.90 deg -----
Thu Dec 07 2017 11:48:21.226747 - lighthouse: Updating tilt for 775ADEB0.1. Old= 24.01, -15.94, 3.27743e-06 <- 0.42 deg -> new= 23.59, -15.90, 4.05965e-06   result=23.59, -15.90, 4.05965e-06
Thu Dec 07 2017 11:48:21.226756 - lighthouse: BootstrapFinished setting tilt base to 775ADEB0
Thu Dec 07 2017 11:48:21.226761 - lighthouse: Selected existing universe 1512584546 (775ADEB0 is primary)
Thu Dec 07 2017 11:48:21.226770 - lighthouse: Setting tilt from 775ADEB0 via transform to global: pitch 23.59 deg roll -15.90 deg
Thu Dec 07 2017 11:48:21.230145 - lighthouse: Saved LighthouseDB rev 198 to /home/carl/.steam/steam/config/lighthouse/lighthousedb.json
Thu Dec 07 2017 11:48:24.911844 - lighthouse: LHR-FF421D45 C: Trying to add a secondary base E2F61B3C: Samples didn't yield successful bootstrap pose
Thu Dec 07 2017 11:48:31.189461 - lighthouse: VRC-D4B105EBBE C: Trying to start tracking from base 775ADEB0: Samples didn't yield successful bootstrap pose
Thu Dec 07 2017 11:48:32.058936 - lighthouse: VRC-D4B105EBBE C: ----- BOOTSTRAPPED base 775ADEB0 (immediate) distance 3.13m velocity 0.01m/s recorded pitch ~23.6 deg roll ~-15.9 deg -----
Thu Dec 07 2017 11:48:32.135386 - 2 - in use time less than now: 0x4873d7f4a5e0  < 0x4873d7f4a567
Thu Dec 07 2017 11:48:33.913399 - 2 - in use time less than now: 0x487441eef6fe  < 0x487441eef504
Thu Dec 07 2017 11:48:34.146779 - lighthouse: VRC-D4B105EBBE C: Calibration failed: no optical samples from base 775ADEB0 for 2004ms
Thu Dec 07 2017 11:48:36.775038 - lighthouse: VRC-D4B105EBBE C: Trying to start tracking from base E2F61B3C: Could boot, but disallowed by LighthouseDB
Thu Dec 07 2017 11:48:39.153008 - lighthouse: VRC-D4B105EBBE C: Trying to start tracking from base 775ADEB0: Not enough contiguous samples for a bootstrap pose
Thu Dec 07 2017 11:48:44.845123 - lighthouse: LHR-FF421D45 C: Resetting tracking: no optical samples from base 775ADEB0 for 2002ms
Thu Dec 07 2017 11:48:44.845166 - lighthouse: Stopped tracking with universe 1512584546
Thu Dec 07 2017 11:48:49.853283 - lighthouse: LHR-FF421D45 C: Trying to start tracking from base 775ADEB0: Not enough contiguous samples for a bootstrap pose
```

**NOTE:** I also confirmed that my Vive udev rules have been written properly, restarted, and am still getting this error.

#### Steps for reproducing this issue:
1. Update Ubuntu 16.04 to Ubuntu 17.10, and install `nvidia-387` package.
2. Launch Vive Room Setup
3. Receive error in picture above.

**Comment by source83** [comment] 2017-12-09 04:08
Same distribution and version, same gpu driver on gtx 1070 turbo.
But in my case, as long as the controllers are switched of, I can start the room setup and get as far as where it tells me to turn on the controllers.
As soon as one of the controllers turns on and registers in the SteamVR dashboard, the room setup dies.

Then again, if one or both controllers are switched on and I try to launch the room setup, it shows up for a short moment, then dies before I can do anything.

It is quite possibly related to or the same underlying problem I stated in #80

**Comment by Goofybud16** [comment] 2020-06-27 01:07
Ubuntu 17.10 has been out of support since July 2018. Since it's EOL/EOS by nearly two years, is this reproducible on a supported version of Ubuntu?

**Comment by kisak-valve** [comment] 2020-08-01 12:57
Closing pending feedback.

**Closed by kisak-valve** 2020-08-01 12:57 UTC
Labels: Need Retest
